/*
 * generated by Xtext 2.44.0
 */
package org.xtext.example.bilang.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.bilang.ide.contentassist.antlr.internal.InternalBilangParser;
import org.xtext.example.bilang.services.BilangGrammarAccess;

public class BilangParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(BilangGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, BilangGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getModelAccess().getAlternatives(), "rule__Model__Alternatives");
			builder.put(grammarAccess.getTaskAccess().getAlternatives(), "rule__Task__Alternatives");
			builder.put(grammarAccess.getRetrieveTaskAccess().getAlternatives(), "rule__RetrieveTask__Alternatives");
			builder.put(grammarAccess.getSendTaskAccess().getAlternatives(), "rule__SendTask__Alternatives");
			builder.put(grammarAccess.getPersonTaskAccess().getAlternatives(), "rule__PersonTask__Alternatives");
			builder.put(grammarAccess.getPersonAccess().getAlternatives(), "rule__Person__Alternatives");
			builder.put(grammarAccess.getContentAccess().getAlternatives(), "rule__Content__Alternatives");
			builder.put(grammarAccess.getDocumentAccess().getAlternatives(), "rule__Document__Alternatives");
			builder.put(grammarAccess.getCompoundProcessAccess().getGroup(), "rule__CompoundProcess__Group__0");
			builder.put(grammarAccess.getCompoundProcessAccess().getGroup_2(), "rule__CompoundProcess__Group_2__0");
			builder.put(grammarAccess.getAbstractProcessAccess().getGroup(), "rule__AbstractProcess__Group__0");
			builder.put(grammarAccess.getParamValueAccess().getGroup(), "rule__ParamValue__Group__0");
			builder.put(grammarAccess.getSendEmailAccess().getGroup(), "rule__SendEmail__Group__0");
			builder.put(grammarAccess.getSendSMSAccess().getGroup(), "rule__SendSMS__Group__0");
			builder.put(grammarAccess.getSendSnailMailAccess().getGroup(), "rule__SendSnailMail__Group__0");
			builder.put(grammarAccess.getRetrieveDocumentAccess().getGroup(), "rule__RetrieveDocument__Group__0");
			builder.put(grammarAccess.getRetrieveFullAddressAccess().getGroup(), "rule__RetrieveFullAddress__Group__0");
			builder.put(grammarAccess.getRetrievePersonsAccess().getGroup(), "rule__RetrievePersons__Group__0");
			builder.put(grammarAccess.getCallPersonAccess().getGroup(), "rule__CallPerson__Group__0");
			builder.put(grammarAccess.getAddPersonAccess().getGroup(), "rule__AddPerson__Group__0");
			builder.put(grammarAccess.getAddPersonAccess().getGroup_2(), "rule__AddPerson__Group_2__0");
			builder.put(grammarAccess.getDeletePersonAccess().getGroup(), "rule__DeletePerson__Group__0");
			builder.put(grammarAccess.getPersonByEmailAccess().getGroup(), "rule__PersonByEmail__Group__0");
			builder.put(grammarAccess.getPersonByAliasAccess().getGroup(), "rule__PersonByAlias__Group__0");
			builder.put(grammarAccess.getPersonByNameAccess().getGroup(), "rule__PersonByName__Group__0");
			builder.put(grammarAccess.getPersonByPhoneAccess().getGroup(), "rule__PersonByPhone__Group__0");
			builder.put(grammarAccess.getPersonByAddressAccess().getGroup(), "rule__PersonByAddress__Group__0");
			builder.put(grammarAccess.getMessageAccess().getGroup(), "rule__Message__Group__0");
			builder.put(grammarAccess.getInvoiceAccess().getGroup(), "rule__Invoice__Group__0");
			builder.put(grammarAccess.getDocumentPersonAccess().getGroup(), "rule__DocumentPerson__Group__0");
			builder.put(grammarAccess.getTextWithSpacesAccess().getGroup(), "rule__TextWithSpaces__Group__0");
			builder.put(grammarAccess.getCompoundProcessAccess().getTaskAssignment_2_1(), "rule__CompoundProcess__TaskAssignment_2_1");
			builder.put(grammarAccess.getAbstractProcessAccess().getNameAssignment_4(), "rule__AbstractProcess__NameAssignment_4");
			builder.put(grammarAccess.getAbstractProcessAccess().getParamValuesAssignment_6(), "rule__AbstractProcess__ParamValuesAssignment_6");
			builder.put(grammarAccess.getParamValueAccess().getParamAssignment_1(), "rule__ParamValue__ParamAssignment_1");
			builder.put(grammarAccess.getParamValueAccess().getValueAssignment_3(), "rule__ParamValue__ValueAssignment_3");
			builder.put(grammarAccess.getSendEmailAccess().getPersonAssignment_4(), "rule__SendEmail__PersonAssignment_4");
			builder.put(grammarAccess.getSendEmailAccess().getContentAssignment_7(), "rule__SendEmail__ContentAssignment_7");
			builder.put(grammarAccess.getSendSMSAccess().getPersonAssignment_4(), "rule__SendSMS__PersonAssignment_4");
			builder.put(grammarAccess.getSendSMSAccess().getContentAssignment_7(), "rule__SendSMS__ContentAssignment_7");
			builder.put(grammarAccess.getSendSnailMailAccess().getPersonAssignment_5(), "rule__SendSnailMail__PersonAssignment_5");
			builder.put(grammarAccess.getSendSnailMailAccess().getContentAssignment_8(), "rule__SendSnailMail__ContentAssignment_8");
			builder.put(grammarAccess.getRetrieveDocumentAccess().getDocumentAssignment_2(), "rule__RetrieveDocument__DocumentAssignment_2");
			builder.put(grammarAccess.getRetrieveFullAddressAccess().getPersonAdressAssignment_4(), "rule__RetrieveFullAddress__PersonAdressAssignment_4");
			builder.put(grammarAccess.getRetrievePersonsAccess().getPersonSearchAssignment_4(), "rule__RetrievePersons__PersonSearchAssignment_4");
			builder.put(grammarAccess.getCallPersonAccess().getPersonAssignment_2(), "rule__CallPerson__PersonAssignment_2");
			builder.put(grammarAccess.getAddPersonAccess().getAliasAssignment_1(), "rule__AddPerson__AliasAssignment_1");
			builder.put(grammarAccess.getAddPersonAccess().getPersonAssignment_2_1(), "rule__AddPerson__PersonAssignment_2_1");
			builder.put(grammarAccess.getDeletePersonAccess().getAliasAssignment_1(), "rule__DeletePerson__AliasAssignment_1");
			builder.put(grammarAccess.getPersonByEmailAccess().getEmailaddressAssignment_3(), "rule__PersonByEmail__EmailaddressAssignment_3");
			builder.put(grammarAccess.getPersonByAliasAccess().getAliasAssignment_3(), "rule__PersonByAlias__AliasAssignment_3");
			builder.put(grammarAccess.getPersonByNameAccess().getFirstNameAssignment_4(), "rule__PersonByName__FirstNameAssignment_4");
			builder.put(grammarAccess.getPersonByNameAccess().getLastNameAssignment_8(), "rule__PersonByName__LastNameAssignment_8");
			builder.put(grammarAccess.getPersonByPhoneAccess().getPhoneAssignment_4(), "rule__PersonByPhone__PhoneAssignment_4");
			builder.put(grammarAccess.getPersonByAddressAccess().getZipcodeAssignment_4(), "rule__PersonByAddress__ZipcodeAssignment_4");
			builder.put(grammarAccess.getPersonByAddressAccess().getHousenumberAssignment_8(), "rule__PersonByAddress__HousenumberAssignment_8");
			builder.put(grammarAccess.getMessageAccess().getMessageAssignment_1(), "rule__Message__MessageAssignment_1");
			builder.put(grammarAccess.getInvoiceAccess().getCodeAssignment_3(), "rule__Invoice__CodeAssignment_3");
			builder.put(grammarAccess.getDocumentPersonAccess().getPersonAssignment_2(), "rule__DocumentPerson__PersonAssignment_2");
			builder.put(grammarAccess.getTextWithSpacesAccess().getPartsAssignment_0(), "rule__TextWithSpaces__PartsAssignment_0");
			builder.put(grammarAccess.getTextWithSpacesAccess().getPartsAssignment_1(), "rule__TextWithSpaces__PartsAssignment_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private BilangGrammarAccess grammarAccess;

	@Override
	protected InternalBilangParser createParser() {
		InternalBilangParser result = new InternalBilangParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public BilangGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(BilangGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
