/*
 * generated by Xtext 2.44.0
 */
package org.xtext.example.bilang.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class BilangGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.bilang.Bilang.Model");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cTaskParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cCompoundProcessParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cAbstractProcessParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Model: Task | CompoundProcess | AbstractProcess;
		@Override public ParserRule getRule() { return rule; }
		
		//Task | CompoundProcess | AbstractProcess
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Task
		public RuleCall getTaskParserRuleCall_0() { return cTaskParserRuleCall_0; }
		
		//CompoundProcess
		public RuleCall getCompoundProcessParserRuleCall_1() { return cCompoundProcessParserRuleCall_1; }
		
		//AbstractProcess
		public RuleCall getAbstractProcessParserRuleCall_2() { return cAbstractProcessParserRuleCall_2; }
	}
	public class TaskElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.bilang.Bilang.Task");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSendTaskParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cRetrieveTaskParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cPersonTaskParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Task: SendTask | RetrieveTask | PersonTask;
		@Override public ParserRule getRule() { return rule; }
		
		//SendTask | RetrieveTask | PersonTask
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//SendTask
		public RuleCall getSendTaskParserRuleCall_0() { return cSendTaskParserRuleCall_0; }
		
		//RetrieveTask
		public RuleCall getRetrieveTaskParserRuleCall_1() { return cRetrieveTaskParserRuleCall_1; }
		
		//PersonTask
		public RuleCall getPersonTaskParserRuleCall_2() { return cPersonTaskParserRuleCall_2; }
	}
	public class CompoundProcessElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.bilang.Bilang.CompoundProcess");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCompoundKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cProcessKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cTaskKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cTaskAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cTaskTaskParserRuleCall_2_1_0 = (RuleCall)cTaskAssignment_2_1.eContents().get(0);
		
		//CompoundProcess: 'compound' 'process' ('task' task+=Task)+;
		@Override public ParserRule getRule() { return rule; }
		
		//'compound' 'process' ('task' task+=Task)+
		public Group getGroup() { return cGroup; }
		
		//'compound'
		public Keyword getCompoundKeyword_0() { return cCompoundKeyword_0; }
		
		//'process'
		public Keyword getProcessKeyword_1() { return cProcessKeyword_1; }
		
		//('task' task+=Task)+
		public Group getGroup_2() { return cGroup_2; }
		
		//'task'
		public Keyword getTaskKeyword_2_0() { return cTaskKeyword_2_0; }
		
		//task+=Task
		public Assignment getTaskAssignment_2_1() { return cTaskAssignment_2_1; }
		
		//Task
		public RuleCall getTaskTaskParserRuleCall_2_1_0() { return cTaskTaskParserRuleCall_2_1_0; }
	}
	public class AbstractProcessElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.bilang.Bilang.AbstractProcess");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAbstractKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cProcessKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cWithKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cNameKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cNameAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cNameIDTerminalRuleCall_4_0 = (RuleCall)cNameAssignment_4.eContents().get(0);
		private final Keyword cAndKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cParamValuesAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cParamValuesParamValueParserRuleCall_6_0 = (RuleCall)cParamValuesAssignment_6.eContents().get(0);
		
		//AbstractProcess: 'abstract' 'process' 'with' 'name' name=ID 'and' paramValues+=ParamValue+;
		@Override public ParserRule getRule() { return rule; }
		
		//'abstract' 'process' 'with' 'name' name=ID 'and' paramValues+=ParamValue+
		public Group getGroup() { return cGroup; }
		
		//'abstract'
		public Keyword getAbstractKeyword_0() { return cAbstractKeyword_0; }
		
		//'process'
		public Keyword getProcessKeyword_1() { return cProcessKeyword_1; }
		
		//'with'
		public Keyword getWithKeyword_2() { return cWithKeyword_2; }
		
		//'name'
		public Keyword getNameKeyword_3() { return cNameKeyword_3; }
		
		//name=ID
		public Assignment getNameAssignment_4() { return cNameAssignment_4; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_4_0() { return cNameIDTerminalRuleCall_4_0; }
		
		//'and'
		public Keyword getAndKeyword_5() { return cAndKeyword_5; }
		
		//paramValues+=ParamValue+
		public Assignment getParamValuesAssignment_6() { return cParamValuesAssignment_6; }
		
		//ParamValue
		public RuleCall getParamValuesParamValueParserRuleCall_6_0() { return cParamValuesParamValueParserRuleCall_6_0; }
	}
	public class ParamValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.bilang.Bilang.ParamValue");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cParameterKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cParamAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cParamIDTerminalRuleCall_1_0 = (RuleCall)cParamAssignment_1.eContents().get(0);
		private final Keyword cValueKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cValueAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cValueIDTerminalRuleCall_3_0 = (RuleCall)cValueAssignment_3.eContents().get(0);
		
		//ParamValue: 'parameter' param=ID 'value' value=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//'parameter' param=ID 'value' value=ID
		public Group getGroup() { return cGroup; }
		
		//'parameter'
		public Keyword getParameterKeyword_0() { return cParameterKeyword_0; }
		
		//param=ID
		public Assignment getParamAssignment_1() { return cParamAssignment_1; }
		
		//ID
		public RuleCall getParamIDTerminalRuleCall_1_0() { return cParamIDTerminalRuleCall_1_0; }
		
		//'value'
		public Keyword getValueKeyword_2() { return cValueKeyword_2; }
		
		//value=ID
		public Assignment getValueAssignment_3() { return cValueAssignment_3; }
		
		//ID
		public RuleCall getValueIDTerminalRuleCall_3_0() { return cValueIDTerminalRuleCall_3_0; }
	}
	public class RetrieveTaskElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.bilang.Bilang.RetrieveTask");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cRetrieveDocumentParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cRetrieveFullAddressParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cRetrievePersonsParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//RetrieveTask: RetrieveDocument | RetrieveFullAddress | RetrievePersons;
		@Override public ParserRule getRule() { return rule; }
		
		//RetrieveDocument | RetrieveFullAddress | RetrievePersons
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//RetrieveDocument
		public RuleCall getRetrieveDocumentParserRuleCall_0() { return cRetrieveDocumentParserRuleCall_0; }
		
		//RetrieveFullAddress
		public RuleCall getRetrieveFullAddressParserRuleCall_1() { return cRetrieveFullAddressParserRuleCall_1; }
		
		//RetrievePersons
		public RuleCall getRetrievePersonsParserRuleCall_2() { return cRetrievePersonsParserRuleCall_2; }
	}
	public class SendTaskElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.bilang.Bilang.SendTask");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSendEmailParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cSendSMSParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cSendSnailMailParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//SendTask: SendEmail | SendSMS | SendSnailMail;
		@Override public ParserRule getRule() { return rule; }
		
		//SendEmail | SendSMS | SendSnailMail
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//SendEmail
		public RuleCall getSendEmailParserRuleCall_0() { return cSendEmailParserRuleCall_0; }
		
		//SendSMS
		public RuleCall getSendSMSParserRuleCall_1() { return cSendSMSParserRuleCall_1; }
		
		//SendSnailMail
		public RuleCall getSendSnailMailParserRuleCall_2() { return cSendSnailMailParserRuleCall_2; }
	}
	public class PersonTaskElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.bilang.Bilang.PersonTask");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cCallPersonParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cAddPersonParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cDeletePersonParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//PersonTask: CallPerson | AddPerson | DeletePerson;
		@Override public ParserRule getRule() { return rule; }
		
		//CallPerson | AddPerson | DeletePerson
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//CallPerson
		public RuleCall getCallPersonParserRuleCall_0() { return cCallPersonParserRuleCall_0; }
		
		//AddPerson
		public RuleCall getAddPersonParserRuleCall_1() { return cAddPersonParserRuleCall_1; }
		
		//DeletePerson
		public RuleCall getDeletePersonParserRuleCall_2() { return cDeletePersonParserRuleCall_2; }
	}
	public class SendEmailElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.bilang.Bilang.SendEmail");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSendKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cAnKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cEmailKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cToKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cPersonAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cPersonPersonParserRuleCall_4_0 = (RuleCall)cPersonAssignment_4.eContents().get(0);
		private final Keyword cWithKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cContentKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cContentAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cContentContentParserRuleCall_7_0 = (RuleCall)cContentAssignment_7.eContents().get(0);
		
		//SendEmail: 'send' 'an' 'email' 'to' person+=Person+ 'with' 'content' content=Content;
		@Override public ParserRule getRule() { return rule; }
		
		//'send' 'an' 'email' 'to' person+=Person+ 'with' 'content' content=Content
		public Group getGroup() { return cGroup; }
		
		//'send'
		public Keyword getSendKeyword_0() { return cSendKeyword_0; }
		
		//'an'
		public Keyword getAnKeyword_1() { return cAnKeyword_1; }
		
		//'email'
		public Keyword getEmailKeyword_2() { return cEmailKeyword_2; }
		
		//'to'
		public Keyword getToKeyword_3() { return cToKeyword_3; }
		
		//person+=Person+
		public Assignment getPersonAssignment_4() { return cPersonAssignment_4; }
		
		//Person
		public RuleCall getPersonPersonParserRuleCall_4_0() { return cPersonPersonParserRuleCall_4_0; }
		
		//'with'
		public Keyword getWithKeyword_5() { return cWithKeyword_5; }
		
		//'content'
		public Keyword getContentKeyword_6() { return cContentKeyword_6; }
		
		//content=Content
		public Assignment getContentAssignment_7() { return cContentAssignment_7; }
		
		//Content
		public RuleCall getContentContentParserRuleCall_7_0() { return cContentContentParserRuleCall_7_0; }
	}
	public class SendSMSElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.bilang.Bilang.SendSMS");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSendKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cAnKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cSmsKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cToKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cPersonAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cPersonPersonParserRuleCall_4_0 = (RuleCall)cPersonAssignment_4.eContents().get(0);
		private final Keyword cWithKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cContentKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cContentAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cContentContentParserRuleCall_7_0 = (RuleCall)cContentAssignment_7.eContents().get(0);
		
		//SendSMS: 'send' 'an' 'sms' 'to' person+=Person+ 'with' 'content' content=Content;
		@Override public ParserRule getRule() { return rule; }
		
		//'send' 'an' 'sms' 'to' person+=Person+ 'with' 'content' content=Content
		public Group getGroup() { return cGroup; }
		
		//'send'
		public Keyword getSendKeyword_0() { return cSendKeyword_0; }
		
		//'an'
		public Keyword getAnKeyword_1() { return cAnKeyword_1; }
		
		//'sms'
		public Keyword getSmsKeyword_2() { return cSmsKeyword_2; }
		
		//'to'
		public Keyword getToKeyword_3() { return cToKeyword_3; }
		
		//person+=Person+
		public Assignment getPersonAssignment_4() { return cPersonAssignment_4; }
		
		//Person
		public RuleCall getPersonPersonParserRuleCall_4_0() { return cPersonPersonParserRuleCall_4_0; }
		
		//'with'
		public Keyword getWithKeyword_5() { return cWithKeyword_5; }
		
		//'content'
		public Keyword getContentKeyword_6() { return cContentKeyword_6; }
		
		//content=Content
		public Assignment getContentAssignment_7() { return cContentAssignment_7; }
		
		//Content
		public RuleCall getContentContentParserRuleCall_7_0() { return cContentContentParserRuleCall_7_0; }
	}
	public class SendSnailMailElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.bilang.Bilang.SendSnailMail");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSendKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cAKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cSnailKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cMailKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cToKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cPersonAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cPersonPersonParserRuleCall_5_0 = (RuleCall)cPersonAssignment_5.eContents().get(0);
		private final Keyword cWithKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cContentKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cContentAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cContentContentParserRuleCall_8_0 = (RuleCall)cContentAssignment_8.eContents().get(0);
		
		//SendSnailMail: 'send' 'a' 'snail' 'mail' 'to' person+=Person+ 'with' 'content' content=Content;
		@Override public ParserRule getRule() { return rule; }
		
		//'send' 'a' 'snail' 'mail' 'to' person+=Person+ 'with' 'content' content=Content
		public Group getGroup() { return cGroup; }
		
		//'send'
		public Keyword getSendKeyword_0() { return cSendKeyword_0; }
		
		//'a'
		public Keyword getAKeyword_1() { return cAKeyword_1; }
		
		//'snail'
		public Keyword getSnailKeyword_2() { return cSnailKeyword_2; }
		
		//'mail'
		public Keyword getMailKeyword_3() { return cMailKeyword_3; }
		
		//'to'
		public Keyword getToKeyword_4() { return cToKeyword_4; }
		
		//person+=Person+
		public Assignment getPersonAssignment_5() { return cPersonAssignment_5; }
		
		//Person
		public RuleCall getPersonPersonParserRuleCall_5_0() { return cPersonPersonParserRuleCall_5_0; }
		
		//'with'
		public Keyword getWithKeyword_6() { return cWithKeyword_6; }
		
		//'content'
		public Keyword getContentKeyword_7() { return cContentKeyword_7; }
		
		//content=Content
		public Assignment getContentAssignment_8() { return cContentAssignment_8; }
		
		//Content
		public RuleCall getContentContentParserRuleCall_8_0() { return cContentContentParserRuleCall_8_0; }
	}
	public class RetrieveDocumentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.bilang.Bilang.RetrieveDocument");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRetrieveKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cDocumentKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cDocumentAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cDocumentDocumentParserRuleCall_2_0 = (RuleCall)cDocumentAssignment_2.eContents().get(0);
		
		//RetrieveDocument: 'retrieve' 'document' document=Document;
		@Override public ParserRule getRule() { return rule; }
		
		//'retrieve' 'document' document=Document
		public Group getGroup() { return cGroup; }
		
		//'retrieve'
		public Keyword getRetrieveKeyword_0() { return cRetrieveKeyword_0; }
		
		//'document'
		public Keyword getDocumentKeyword_1() { return cDocumentKeyword_1; }
		
		//document=Document
		public Assignment getDocumentAssignment_2() { return cDocumentAssignment_2; }
		
		//Document
		public RuleCall getDocumentDocumentParserRuleCall_2_0() { return cDocumentDocumentParserRuleCall_2_0; }
	}
	public class RetrieveFullAddressElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.bilang.Bilang.RetrieveFullAddress");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRetrieveKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cFullKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cAddressKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cOfKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cPersonAdressAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cPersonAdressPersonByAddressParserRuleCall_4_0 = (RuleCall)cPersonAdressAssignment_4.eContents().get(0);
		
		//RetrieveFullAddress: 'retrieve' 'full' 'address' 'of' personAdress=PersonByAddress;
		@Override public ParserRule getRule() { return rule; }
		
		//'retrieve' 'full' 'address' 'of' personAdress=PersonByAddress
		public Group getGroup() { return cGroup; }
		
		//'retrieve'
		public Keyword getRetrieveKeyword_0() { return cRetrieveKeyword_0; }
		
		//'full'
		public Keyword getFullKeyword_1() { return cFullKeyword_1; }
		
		//'address'
		public Keyword getAddressKeyword_2() { return cAddressKeyword_2; }
		
		//'of'
		public Keyword getOfKeyword_3() { return cOfKeyword_3; }
		
		//personAdress=PersonByAddress
		public Assignment getPersonAdressAssignment_4() { return cPersonAdressAssignment_4; }
		
		//PersonByAddress
		public RuleCall getPersonAdressPersonByAddressParserRuleCall_4_0() { return cPersonAdressPersonByAddressParserRuleCall_4_0; }
	}
	public class RetrievePersonsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.bilang.Bilang.RetrievePersons");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRetrieveKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cPersonsKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cWithKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cSearchKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cPersonSearchAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cPersonSearchIDTerminalRuleCall_4_0 = (RuleCall)cPersonSearchAssignment_4.eContents().get(0);
		
		//RetrievePersons: 'retrieve' 'persons' 'with' 'search' personSearch=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//'retrieve' 'persons' 'with' 'search' personSearch=ID
		public Group getGroup() { return cGroup; }
		
		//'retrieve'
		public Keyword getRetrieveKeyword_0() { return cRetrieveKeyword_0; }
		
		//'persons'
		public Keyword getPersonsKeyword_1() { return cPersonsKeyword_1; }
		
		//'with'
		public Keyword getWithKeyword_2() { return cWithKeyword_2; }
		
		//'search'
		public Keyword getSearchKeyword_3() { return cSearchKeyword_3; }
		
		//personSearch=ID
		public Assignment getPersonSearchAssignment_4() { return cPersonSearchAssignment_4; }
		
		//ID
		public RuleCall getPersonSearchIDTerminalRuleCall_4_0() { return cPersonSearchIDTerminalRuleCall_4_0; }
	}
	public class CallPersonElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.bilang.Bilang.CallPerson");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPhoneKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cCallKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cPersonAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cPersonPersonParserRuleCall_2_0 = (RuleCall)cPersonAssignment_2.eContents().get(0);
		
		//CallPerson: 'phone' 'call' person=Person;
		@Override public ParserRule getRule() { return rule; }
		
		//'phone' 'call' person=Person
		public Group getGroup() { return cGroup; }
		
		//'phone'
		public Keyword getPhoneKeyword_0() { return cPhoneKeyword_0; }
		
		//'call'
		public Keyword getCallKeyword_1() { return cCallKeyword_1; }
		
		//person=Person
		public Assignment getPersonAssignment_2() { return cPersonAssignment_2; }
		
		//Person
		public RuleCall getPersonPersonParserRuleCall_2_0() { return cPersonPersonParserRuleCall_2_0; }
	}
	public class AddPersonElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.bilang.Bilang.AddPerson");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAddKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cAliasAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cAliasPersonByAliasParserRuleCall_1_0 = (RuleCall)cAliasAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cAndKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cPersonAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cPersonPersonParserRuleCall_2_1_0 = (RuleCall)cPersonAssignment_2_1.eContents().get(0);
		
		//AddPerson: 'add' alias=PersonByAlias ('and' person+=Person)+;
		@Override public ParserRule getRule() { return rule; }
		
		//'add' alias=PersonByAlias ('and' person+=Person)+
		public Group getGroup() { return cGroup; }
		
		//'add'
		public Keyword getAddKeyword_0() { return cAddKeyword_0; }
		
		//alias=PersonByAlias
		public Assignment getAliasAssignment_1() { return cAliasAssignment_1; }
		
		//PersonByAlias
		public RuleCall getAliasPersonByAliasParserRuleCall_1_0() { return cAliasPersonByAliasParserRuleCall_1_0; }
		
		//('and' person+=Person)+
		public Group getGroup_2() { return cGroup_2; }
		
		//'and'
		public Keyword getAndKeyword_2_0() { return cAndKeyword_2_0; }
		
		//person+=Person
		public Assignment getPersonAssignment_2_1() { return cPersonAssignment_2_1; }
		
		//Person
		public RuleCall getPersonPersonParserRuleCall_2_1_0() { return cPersonPersonParserRuleCall_2_1_0; }
	}
	public class DeletePersonElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.bilang.Bilang.DeletePerson");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDeleteKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cAliasAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cAliasPersonByAliasParserRuleCall_1_0 = (RuleCall)cAliasAssignment_1.eContents().get(0);
		
		//DeletePerson: 'delete' alias=PersonByAlias;
		@Override public ParserRule getRule() { return rule; }
		
		//'delete' alias=PersonByAlias
		public Group getGroup() { return cGroup; }
		
		//'delete'
		public Keyword getDeleteKeyword_0() { return cDeleteKeyword_0; }
		
		//alias=PersonByAlias
		public Assignment getAliasAssignment_1() { return cAliasAssignment_1; }
		
		//PersonByAlias
		public RuleCall getAliasPersonByAliasParserRuleCall_1_0() { return cAliasPersonByAliasParserRuleCall_1_0; }
	}
	public class PersonElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.bilang.Bilang.Person");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cPersonByEmailParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cPersonByAliasParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cPersonByNameParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cPersonByPhoneParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cPersonByAddressParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		
		//Person: PersonByEmail | PersonByAlias | PersonByName | PersonByPhone | PersonByAddress;
		@Override public ParserRule getRule() { return rule; }
		
		//PersonByEmail | PersonByAlias | PersonByName | PersonByPhone | PersonByAddress
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//PersonByEmail
		public RuleCall getPersonByEmailParserRuleCall_0() { return cPersonByEmailParserRuleCall_0; }
		
		//PersonByAlias
		public RuleCall getPersonByAliasParserRuleCall_1() { return cPersonByAliasParserRuleCall_1; }
		
		//PersonByName
		public RuleCall getPersonByNameParserRuleCall_2() { return cPersonByNameParserRuleCall_2; }
		
		//PersonByPhone
		public RuleCall getPersonByPhoneParserRuleCall_3() { return cPersonByPhoneParserRuleCall_3; }
		
		//PersonByAddress
		public RuleCall getPersonByAddressParserRuleCall_4() { return cPersonByAddressParserRuleCall_4; }
	}
	public class PersonByEmailElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.bilang.Bilang.PersonByEmail");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPersonKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cWithKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cEmailKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cEmailaddressAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cEmailaddressEMAIL_ADDRESSTerminalRuleCall_3_0 = (RuleCall)cEmailaddressAssignment_3.eContents().get(0);
		
		//PersonByEmail: 'person' 'with' 'email' emailaddress=EMAIL_ADDRESS;
		@Override public ParserRule getRule() { return rule; }
		
		//'person' 'with' 'email' emailaddress=EMAIL_ADDRESS
		public Group getGroup() { return cGroup; }
		
		//'person'
		public Keyword getPersonKeyword_0() { return cPersonKeyword_0; }
		
		//'with'
		public Keyword getWithKeyword_1() { return cWithKeyword_1; }
		
		//'email'
		public Keyword getEmailKeyword_2() { return cEmailKeyword_2; }
		
		//emailaddress=EMAIL_ADDRESS
		public Assignment getEmailaddressAssignment_3() { return cEmailaddressAssignment_3; }
		
		//EMAIL_ADDRESS
		public RuleCall getEmailaddressEMAIL_ADDRESSTerminalRuleCall_3_0() { return cEmailaddressEMAIL_ADDRESSTerminalRuleCall_3_0; }
	}
	public class PersonByAliasElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.bilang.Bilang.PersonByAlias");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPersonKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cWithKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cAliasKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cAliasAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cAliasIDTerminalRuleCall_3_0 = (RuleCall)cAliasAssignment_3.eContents().get(0);
		
		//PersonByAlias: 'person' 'with' 'alias' alias=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//'person' 'with' 'alias' alias=ID
		public Group getGroup() { return cGroup; }
		
		//'person'
		public Keyword getPersonKeyword_0() { return cPersonKeyword_0; }
		
		//'with'
		public Keyword getWithKeyword_1() { return cWithKeyword_1; }
		
		//'alias'
		public Keyword getAliasKeyword_2() { return cAliasKeyword_2; }
		
		//alias=ID
		public Assignment getAliasAssignment_3() { return cAliasAssignment_3; }
		
		//ID
		public RuleCall getAliasIDTerminalRuleCall_3_0() { return cAliasIDTerminalRuleCall_3_0; }
	}
	public class PersonByNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.bilang.Bilang.PersonByName");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPersonKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cWithKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cFirstKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cNameKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cFirstNameAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cFirstNameIDTerminalRuleCall_4_0 = (RuleCall)cFirstNameAssignment_4.eContents().get(0);
		private final Keyword cAndKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cLastKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cNameKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cLastNameAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cLastNameTextWithSpacesParserRuleCall_8_0 = (RuleCall)cLastNameAssignment_8.eContents().get(0);
		
		//PersonByName: 'person' 'with' 'first' 'name' firstName=ID 'and' 'last' 'name' lastName=TextWithSpaces;
		@Override public ParserRule getRule() { return rule; }
		
		//'person' 'with' 'first' 'name' firstName=ID 'and' 'last' 'name' lastName=TextWithSpaces
		public Group getGroup() { return cGroup; }
		
		//'person'
		public Keyword getPersonKeyword_0() { return cPersonKeyword_0; }
		
		//'with'
		public Keyword getWithKeyword_1() { return cWithKeyword_1; }
		
		//'first'
		public Keyword getFirstKeyword_2() { return cFirstKeyword_2; }
		
		//'name'
		public Keyword getNameKeyword_3() { return cNameKeyword_3; }
		
		//firstName=ID
		public Assignment getFirstNameAssignment_4() { return cFirstNameAssignment_4; }
		
		//ID
		public RuleCall getFirstNameIDTerminalRuleCall_4_0() { return cFirstNameIDTerminalRuleCall_4_0; }
		
		//'and'
		public Keyword getAndKeyword_5() { return cAndKeyword_5; }
		
		//'last'
		public Keyword getLastKeyword_6() { return cLastKeyword_6; }
		
		//'name'
		public Keyword getNameKeyword_7() { return cNameKeyword_7; }
		
		//lastName=TextWithSpaces
		public Assignment getLastNameAssignment_8() { return cLastNameAssignment_8; }
		
		//TextWithSpaces
		public RuleCall getLastNameTextWithSpacesParserRuleCall_8_0() { return cLastNameTextWithSpacesParserRuleCall_8_0; }
	}
	public class PersonByPhoneElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.bilang.Bilang.PersonByPhone");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPersonKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cWithKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cPhoneKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cNumberKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cPhoneAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cPhonePHONE_NUMBERTerminalRuleCall_4_0 = (RuleCall)cPhoneAssignment_4.eContents().get(0);
		
		//PersonByPhone: 'person' 'with' 'phone' 'number' phone=PHONE_NUMBER;
		@Override public ParserRule getRule() { return rule; }
		
		//'person' 'with' 'phone' 'number' phone=PHONE_NUMBER
		public Group getGroup() { return cGroup; }
		
		//'person'
		public Keyword getPersonKeyword_0() { return cPersonKeyword_0; }
		
		//'with'
		public Keyword getWithKeyword_1() { return cWithKeyword_1; }
		
		//'phone'
		public Keyword getPhoneKeyword_2() { return cPhoneKeyword_2; }
		
		//'number'
		public Keyword getNumberKeyword_3() { return cNumberKeyword_3; }
		
		//phone=PHONE_NUMBER
		public Assignment getPhoneAssignment_4() { return cPhoneAssignment_4; }
		
		//PHONE_NUMBER
		public RuleCall getPhonePHONE_NUMBERTerminalRuleCall_4_0() { return cPhonePHONE_NUMBERTerminalRuleCall_4_0; }
	}
	public class PersonByAddressElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.bilang.Bilang.PersonByAddress");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPersonKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cWithKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cZipKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cCodeKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cZipcodeAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cZipcodeDUTCH_POSTCODETerminalRuleCall_4_0 = (RuleCall)cZipcodeAssignment_4.eContents().get(0);
		private final Keyword cAndKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cHouseKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cNumberKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cHousenumberAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cHousenumberHOUSENUMBERTerminalRuleCall_8_0 = (RuleCall)cHousenumberAssignment_8.eContents().get(0);
		
		//PersonByAddress: 'person' 'with' 'zip' 'code' zipcode=DUTCH_POSTCODE 'and' 'house' 'number' housenumber=HOUSENUMBER;
		@Override public ParserRule getRule() { return rule; }
		
		//'person' 'with' 'zip' 'code' zipcode=DUTCH_POSTCODE 'and' 'house' 'number' housenumber=HOUSENUMBER
		public Group getGroup() { return cGroup; }
		
		//'person'
		public Keyword getPersonKeyword_0() { return cPersonKeyword_0; }
		
		//'with'
		public Keyword getWithKeyword_1() { return cWithKeyword_1; }
		
		//'zip'
		public Keyword getZipKeyword_2() { return cZipKeyword_2; }
		
		//'code'
		public Keyword getCodeKeyword_3() { return cCodeKeyword_3; }
		
		//zipcode=DUTCH_POSTCODE
		public Assignment getZipcodeAssignment_4() { return cZipcodeAssignment_4; }
		
		//DUTCH_POSTCODE
		public RuleCall getZipcodeDUTCH_POSTCODETerminalRuleCall_4_0() { return cZipcodeDUTCH_POSTCODETerminalRuleCall_4_0; }
		
		//'and'
		public Keyword getAndKeyword_5() { return cAndKeyword_5; }
		
		//'house'
		public Keyword getHouseKeyword_6() { return cHouseKeyword_6; }
		
		//'number'
		public Keyword getNumberKeyword_7() { return cNumberKeyword_7; }
		
		//housenumber=HOUSENUMBER
		public Assignment getHousenumberAssignment_8() { return cHousenumberAssignment_8; }
		
		//HOUSENUMBER
		public RuleCall getHousenumberHOUSENUMBERTerminalRuleCall_8_0() { return cHousenumberHOUSENUMBERTerminalRuleCall_8_0; }
	}
	public class ContentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.bilang.Bilang.Content");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cMessageParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cDocumentParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Content: Message | Document;
		@Override public ParserRule getRule() { return rule; }
		
		//Message | Document
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Message
		public RuleCall getMessageParserRuleCall_0() { return cMessageParserRuleCall_0; }
		
		//Document
		public RuleCall getDocumentParserRuleCall_1() { return cDocumentParserRuleCall_1; }
	}
	public class MessageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.bilang.Bilang.Message");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cMessageKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cMessageAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cMessageTextWithSpacesParserRuleCall_1_0 = (RuleCall)cMessageAssignment_1.eContents().get(0);
		
		//Message: 'message' message=TextWithSpaces;
		@Override public ParserRule getRule() { return rule; }
		
		//'message' message=TextWithSpaces
		public Group getGroup() { return cGroup; }
		
		//'message'
		public Keyword getMessageKeyword_0() { return cMessageKeyword_0; }
		
		//message=TextWithSpaces
		public Assignment getMessageAssignment_1() { return cMessageAssignment_1; }
		
		//TextWithSpaces
		public RuleCall getMessageTextWithSpacesParserRuleCall_1_0() { return cMessageTextWithSpacesParserRuleCall_1_0; }
	}
	public class DocumentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.bilang.Bilang.Document");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cInvoiceParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cDocumentPersonParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Document: Invoice | DocumentPerson;
		@Override public ParserRule getRule() { return rule; }
		
		//Invoice | DocumentPerson
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Invoice
		public RuleCall getInvoiceParserRuleCall_0() { return cInvoiceParserRuleCall_0; }
		
		//DocumentPerson
		public RuleCall getDocumentPersonParserRuleCall_1() { return cDocumentPersonParserRuleCall_1; }
	}
	public class InvoiceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.bilang.Bilang.Invoice");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cInvoiceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cWithKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cCodeKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cCodeAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cCodeINTTerminalRuleCall_3_0 = (RuleCall)cCodeAssignment_3.eContents().get(0);
		
		//Invoice: 'invoice' 'with' 'code' code=INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'invoice' 'with' 'code' code=INT
		public Group getGroup() { return cGroup; }
		
		//'invoice'
		public Keyword getInvoiceKeyword_0() { return cInvoiceKeyword_0; }
		
		//'with'
		public Keyword getWithKeyword_1() { return cWithKeyword_1; }
		
		//'code'
		public Keyword getCodeKeyword_2() { return cCodeKeyword_2; }
		
		//code=INT
		public Assignment getCodeAssignment_3() { return cCodeAssignment_3; }
		
		//INT
		public RuleCall getCodeINTTerminalRuleCall_3_0() { return cCodeINTTerminalRuleCall_3_0; }
	}
	public class DocumentPersonElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.bilang.Bilang.DocumentPerson");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cInformationKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cAboutKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cPersonAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cPersonPersonParserRuleCall_2_0 = (RuleCall)cPersonAssignment_2.eContents().get(0);
		
		//DocumentPerson: 'information' 'about' person=Person;
		@Override public ParserRule getRule() { return rule; }
		
		//'information' 'about' person=Person
		public Group getGroup() { return cGroup; }
		
		//'information'
		public Keyword getInformationKeyword_0() { return cInformationKeyword_0; }
		
		//'about'
		public Keyword getAboutKeyword_1() { return cAboutKeyword_1; }
		
		//person=Person
		public Assignment getPersonAssignment_2() { return cPersonAssignment_2; }
		
		//Person
		public RuleCall getPersonPersonParserRuleCall_2_0() { return cPersonPersonParserRuleCall_2_0; }
	}
	public class TextWithSpacesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.bilang.Bilang.TextWithSpaces");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cPartsAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cPartsIDTerminalRuleCall_0_0 = (RuleCall)cPartsAssignment_0.eContents().get(0);
		private final Assignment cPartsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cPartsIDTerminalRuleCall_1_0 = (RuleCall)cPartsAssignment_1.eContents().get(0);
		
		//TextWithSpaces: parts+=ID parts+=ID+;
		@Override public ParserRule getRule() { return rule; }
		
		//parts+=ID parts+=ID+
		public Group getGroup() { return cGroup; }
		
		//parts+=ID
		public Assignment getPartsAssignment_0() { return cPartsAssignment_0; }
		
		//ID
		public RuleCall getPartsIDTerminalRuleCall_0_0() { return cPartsIDTerminalRuleCall_0_0; }
		
		//parts+=ID+
		public Assignment getPartsAssignment_1() { return cPartsAssignment_1; }
		
		//ID
		public RuleCall getPartsIDTerminalRuleCall_1_0() { return cPartsIDTerminalRuleCall_1_0; }
	}
	
	
	private final ModelElements pModel;
	private final TaskElements pTask;
	private final CompoundProcessElements pCompoundProcess;
	private final AbstractProcessElements pAbstractProcess;
	private final ParamValueElements pParamValue;
	private final RetrieveTaskElements pRetrieveTask;
	private final SendTaskElements pSendTask;
	private final PersonTaskElements pPersonTask;
	private final SendEmailElements pSendEmail;
	private final SendSMSElements pSendSMS;
	private final SendSnailMailElements pSendSnailMail;
	private final RetrieveDocumentElements pRetrieveDocument;
	private final RetrieveFullAddressElements pRetrieveFullAddress;
	private final RetrievePersonsElements pRetrievePersons;
	private final CallPersonElements pCallPerson;
	private final AddPersonElements pAddPerson;
	private final DeletePersonElements pDeletePerson;
	private final PersonElements pPerson;
	private final PersonByEmailElements pPersonByEmail;
	private final PersonByAliasElements pPersonByAlias;
	private final PersonByNameElements pPersonByName;
	private final PersonByPhoneElements pPersonByPhone;
	private final PersonByAddressElements pPersonByAddress;
	private final ContentElements pContent;
	private final MessageElements pMessage;
	private final DocumentElements pDocument;
	private final InvoiceElements pInvoice;
	private final DocumentPersonElements pDocumentPerson;
	private final TerminalRule tEMAIL_ADDRESS;
	private final TerminalRule tPHONE_NUMBER;
	private final TerminalRule tHOUSENUMBER;
	private final TextWithSpacesElements pTextWithSpaces;
	private final TerminalRule tDUTCH_POSTCODE;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public BilangGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pTask = new TaskElements();
		this.pCompoundProcess = new CompoundProcessElements();
		this.pAbstractProcess = new AbstractProcessElements();
		this.pParamValue = new ParamValueElements();
		this.pRetrieveTask = new RetrieveTaskElements();
		this.pSendTask = new SendTaskElements();
		this.pPersonTask = new PersonTaskElements();
		this.pSendEmail = new SendEmailElements();
		this.pSendSMS = new SendSMSElements();
		this.pSendSnailMail = new SendSnailMailElements();
		this.pRetrieveDocument = new RetrieveDocumentElements();
		this.pRetrieveFullAddress = new RetrieveFullAddressElements();
		this.pRetrievePersons = new RetrievePersonsElements();
		this.pCallPerson = new CallPersonElements();
		this.pAddPerson = new AddPersonElements();
		this.pDeletePerson = new DeletePersonElements();
		this.pPerson = new PersonElements();
		this.pPersonByEmail = new PersonByEmailElements();
		this.pPersonByAlias = new PersonByAliasElements();
		this.pPersonByName = new PersonByNameElements();
		this.pPersonByPhone = new PersonByPhoneElements();
		this.pPersonByAddress = new PersonByAddressElements();
		this.pContent = new ContentElements();
		this.pMessage = new MessageElements();
		this.pDocument = new DocumentElements();
		this.pInvoice = new InvoiceElements();
		this.pDocumentPerson = new DocumentPersonElements();
		this.tEMAIL_ADDRESS = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.bilang.Bilang.EMAIL_ADDRESS");
		this.tPHONE_NUMBER = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.bilang.Bilang.PHONE_NUMBER");
		this.tHOUSENUMBER = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.bilang.Bilang.HOUSENUMBER");
		this.pTextWithSpaces = new TextWithSpacesElements();
		this.tDUTCH_POSTCODE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.bilang.Bilang.DUTCH_POSTCODE");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.bilang.Bilang".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model: Task | CompoundProcess | AbstractProcess;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//Task: SendTask | RetrieveTask | PersonTask;
	public TaskElements getTaskAccess() {
		return pTask;
	}
	
	public ParserRule getTaskRule() {
		return getTaskAccess().getRule();
	}
	
	//CompoundProcess: 'compound' 'process' ('task' task+=Task)+;
	public CompoundProcessElements getCompoundProcessAccess() {
		return pCompoundProcess;
	}
	
	public ParserRule getCompoundProcessRule() {
		return getCompoundProcessAccess().getRule();
	}
	
	//AbstractProcess: 'abstract' 'process' 'with' 'name' name=ID 'and' paramValues+=ParamValue+;
	public AbstractProcessElements getAbstractProcessAccess() {
		return pAbstractProcess;
	}
	
	public ParserRule getAbstractProcessRule() {
		return getAbstractProcessAccess().getRule();
	}
	
	//ParamValue: 'parameter' param=ID 'value' value=ID;
	public ParamValueElements getParamValueAccess() {
		return pParamValue;
	}
	
	public ParserRule getParamValueRule() {
		return getParamValueAccess().getRule();
	}
	
	//RetrieveTask: RetrieveDocument | RetrieveFullAddress | RetrievePersons;
	public RetrieveTaskElements getRetrieveTaskAccess() {
		return pRetrieveTask;
	}
	
	public ParserRule getRetrieveTaskRule() {
		return getRetrieveTaskAccess().getRule();
	}
	
	//SendTask: SendEmail | SendSMS | SendSnailMail;
	public SendTaskElements getSendTaskAccess() {
		return pSendTask;
	}
	
	public ParserRule getSendTaskRule() {
		return getSendTaskAccess().getRule();
	}
	
	//PersonTask: CallPerson | AddPerson | DeletePerson;
	public PersonTaskElements getPersonTaskAccess() {
		return pPersonTask;
	}
	
	public ParserRule getPersonTaskRule() {
		return getPersonTaskAccess().getRule();
	}
	
	//SendEmail: 'send' 'an' 'email' 'to' person+=Person+ 'with' 'content' content=Content;
	public SendEmailElements getSendEmailAccess() {
		return pSendEmail;
	}
	
	public ParserRule getSendEmailRule() {
		return getSendEmailAccess().getRule();
	}
	
	//SendSMS: 'send' 'an' 'sms' 'to' person+=Person+ 'with' 'content' content=Content;
	public SendSMSElements getSendSMSAccess() {
		return pSendSMS;
	}
	
	public ParserRule getSendSMSRule() {
		return getSendSMSAccess().getRule();
	}
	
	//SendSnailMail: 'send' 'a' 'snail' 'mail' 'to' person+=Person+ 'with' 'content' content=Content;
	public SendSnailMailElements getSendSnailMailAccess() {
		return pSendSnailMail;
	}
	
	public ParserRule getSendSnailMailRule() {
		return getSendSnailMailAccess().getRule();
	}
	
	//RetrieveDocument: 'retrieve' 'document' document=Document;
	public RetrieveDocumentElements getRetrieveDocumentAccess() {
		return pRetrieveDocument;
	}
	
	public ParserRule getRetrieveDocumentRule() {
		return getRetrieveDocumentAccess().getRule();
	}
	
	//RetrieveFullAddress: 'retrieve' 'full' 'address' 'of' personAdress=PersonByAddress;
	public RetrieveFullAddressElements getRetrieveFullAddressAccess() {
		return pRetrieveFullAddress;
	}
	
	public ParserRule getRetrieveFullAddressRule() {
		return getRetrieveFullAddressAccess().getRule();
	}
	
	//RetrievePersons: 'retrieve' 'persons' 'with' 'search' personSearch=ID;
	public RetrievePersonsElements getRetrievePersonsAccess() {
		return pRetrievePersons;
	}
	
	public ParserRule getRetrievePersonsRule() {
		return getRetrievePersonsAccess().getRule();
	}
	
	//CallPerson: 'phone' 'call' person=Person;
	public CallPersonElements getCallPersonAccess() {
		return pCallPerson;
	}
	
	public ParserRule getCallPersonRule() {
		return getCallPersonAccess().getRule();
	}
	
	//AddPerson: 'add' alias=PersonByAlias ('and' person+=Person)+;
	public AddPersonElements getAddPersonAccess() {
		return pAddPerson;
	}
	
	public ParserRule getAddPersonRule() {
		return getAddPersonAccess().getRule();
	}
	
	//DeletePerson: 'delete' alias=PersonByAlias;
	public DeletePersonElements getDeletePersonAccess() {
		return pDeletePerson;
	}
	
	public ParserRule getDeletePersonRule() {
		return getDeletePersonAccess().getRule();
	}
	
	//Person: PersonByEmail | PersonByAlias | PersonByName | PersonByPhone | PersonByAddress;
	public PersonElements getPersonAccess() {
		return pPerson;
	}
	
	public ParserRule getPersonRule() {
		return getPersonAccess().getRule();
	}
	
	//PersonByEmail: 'person' 'with' 'email' emailaddress=EMAIL_ADDRESS;
	public PersonByEmailElements getPersonByEmailAccess() {
		return pPersonByEmail;
	}
	
	public ParserRule getPersonByEmailRule() {
		return getPersonByEmailAccess().getRule();
	}
	
	//PersonByAlias: 'person' 'with' 'alias' alias=ID;
	public PersonByAliasElements getPersonByAliasAccess() {
		return pPersonByAlias;
	}
	
	public ParserRule getPersonByAliasRule() {
		return getPersonByAliasAccess().getRule();
	}
	
	//PersonByName: 'person' 'with' 'first' 'name' firstName=ID 'and' 'last' 'name' lastName=TextWithSpaces;
	public PersonByNameElements getPersonByNameAccess() {
		return pPersonByName;
	}
	
	public ParserRule getPersonByNameRule() {
		return getPersonByNameAccess().getRule();
	}
	
	//PersonByPhone: 'person' 'with' 'phone' 'number' phone=PHONE_NUMBER;
	public PersonByPhoneElements getPersonByPhoneAccess() {
		return pPersonByPhone;
	}
	
	public ParserRule getPersonByPhoneRule() {
		return getPersonByPhoneAccess().getRule();
	}
	
	//PersonByAddress: 'person' 'with' 'zip' 'code' zipcode=DUTCH_POSTCODE 'and' 'house' 'number' housenumber=HOUSENUMBER;
	public PersonByAddressElements getPersonByAddressAccess() {
		return pPersonByAddress;
	}
	
	public ParserRule getPersonByAddressRule() {
		return getPersonByAddressAccess().getRule();
	}
	
	//Content: Message | Document;
	public ContentElements getContentAccess() {
		return pContent;
	}
	
	public ParserRule getContentRule() {
		return getContentAccess().getRule();
	}
	
	//Message: 'message' message=TextWithSpaces;
	public MessageElements getMessageAccess() {
		return pMessage;
	}
	
	public ParserRule getMessageRule() {
		return getMessageAccess().getRule();
	}
	
	//Document: Invoice | DocumentPerson;
	public DocumentElements getDocumentAccess() {
		return pDocument;
	}
	
	public ParserRule getDocumentRule() {
		return getDocumentAccess().getRule();
	}
	
	//Invoice: 'invoice' 'with' 'code' code=INT;
	public InvoiceElements getInvoiceAccess() {
		return pInvoice;
	}
	
	public ParserRule getInvoiceRule() {
		return getInvoiceAccess().getRule();
	}
	
	//DocumentPerson: 'information' 'about' person=Person;
	public DocumentPersonElements getDocumentPersonAccess() {
		return pDocumentPerson;
	}
	
	public ParserRule getDocumentPersonRule() {
		return getDocumentPersonAccess().getRule();
	}
	
	//terminal EMAIL_ADDRESS:
	//    ('a'..'z' | 'A'..'Z' | '0'..'9' | '_' | '-' | '.')+
	//    '@'
	//    ('a'..'z' | 'A'..'Z' | '0'..'9' | '-' | '.')+;
	public TerminalRule getEMAIL_ADDRESSRule() {
		return tEMAIL_ADDRESS;
	}
	
	//terminal PHONE_NUMBER: '+' ('0'..'9')+;
	public TerminalRule getPHONE_NUMBERRule() {
		return tPHONE_NUMBER;
	}
	
	//terminal HOUSENUMBER:
	//    ('0'..'9')+ ('a'..'z' | 'A'..'Z')?;
	public TerminalRule getHOUSENUMBERRule() {
		return tHOUSENUMBER;
	}
	
	//TextWithSpaces: parts+=ID parts+=ID+;
	public TextWithSpacesElements getTextWithSpacesAccess() {
		return pTextWithSpaces;
	}
	
	public ParserRule getTextWithSpacesRule() {
		return getTextWithSpacesAccess().getRule();
	}
	
	//terminal DUTCH_POSTCODE: ('0'..'9') ('0'..'9') ('0'..'9') ('0'..'9') ' '? ('A'..'Z') ('A'..'Z');
	public TerminalRule getDUTCH_POSTCODERule() {
		return tDUTCH_POSTCODE;
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
