/*
 * generated by Xtext 2.44.0
 */
grammar InternalBilang;

options {
	superClass=AbstractInternalAntlrParser;
}

@lexer::header {
package org.xtext.example.bilang.parser.antlr.internal;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.parser.antlr.Lexer;
}

@parser::header {
package org.xtext.example.bilang.parser.antlr.internal;

import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.parser.antlr.AbstractInternalAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken;
import org.xtext.example.bilang.services.BilangGrammarAccess;

}

@parser::members {

 	private BilangGrammarAccess grammarAccess;

    public InternalBilangParser(TokenStream input, BilangGrammarAccess grammarAccess) {
        this(input);
        this.grammarAccess = grammarAccess;
        registerRules(grammarAccess.getGrammar());
    }

    @Override
    protected String getFirstRuleName() {
    	return "Model";
   	}

   	@Override
   	protected BilangGrammarAccess getGrammarAccess() {
   		return grammarAccess;
   	}

}

@rulecatch {
    catch (RecognitionException re) {
        recover(input,re);
        appendSkippedTokens();
    }
}

// Entry rule entryRuleModel
entryRuleModel returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getModelRule()); }
	iv_ruleModel=ruleModel
	{ $current=$iv_ruleModel.current; }
	EOF;

// Rule Model
ruleModel returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		{
			newCompositeNode(grammarAccess.getModelAccess().getTaskParserRuleCall_0());
		}
		this_Task_0=ruleTask
		{
			$current = $this_Task_0.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getModelAccess().getCompoundProcessParserRuleCall_1());
		}
		this_CompoundProcess_1=ruleCompoundProcess
		{
			$current = $this_CompoundProcess_1.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getModelAccess().getAbstractProcessParserRuleCall_2());
		}
		this_AbstractProcess_2=ruleAbstractProcess
		{
			$current = $this_AbstractProcess_2.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getModelAccess().getEmptyProcessParserRuleCall_3());
		}
		ruleEmptyProcess
		{
			afterParserOrEnumRuleCall();
		}
	)
;

// Entry rule entryRuleTask
entryRuleTask returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getTaskRule()); }
	iv_ruleTask=ruleTask
	{ $current=$iv_ruleTask.current; }
	EOF;

// Rule Task
ruleTask returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='task'
		{
			newLeafNode(otherlv_0, grammarAccess.getTaskAccess().getTaskKeyword_0());
		}
		(
			(
				(
					{
						newCompositeNode(grammarAccess.getTaskAccess().getKindSendTaskParserRuleCall_1_0_0());
					}
					lv_kind_1_1=ruleSendTask
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getTaskRule());
						}
						add(
							$current,
							"kind",
							lv_kind_1_1,
							"org.xtext.example.bilang.Bilang.SendTask");
						afterParserOrEnumRuleCall();
					}
					    |
					{
						newCompositeNode(grammarAccess.getTaskAccess().getKindRetrieveTaskParserRuleCall_1_0_1());
					}
					lv_kind_1_2=ruleRetrieveTask
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getTaskRule());
						}
						add(
							$current,
							"kind",
							lv_kind_1_2,
							"org.xtext.example.bilang.Bilang.RetrieveTask");
						afterParserOrEnumRuleCall();
					}
					    |
					{
						newCompositeNode(grammarAccess.getTaskAccess().getKindPersonTaskParserRuleCall_1_0_2());
					}
					lv_kind_1_3=rulePersonTask
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getTaskRule());
						}
						add(
							$current,
							"kind",
							lv_kind_1_3,
							"org.xtext.example.bilang.Bilang.PersonTask");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)
	)
;

// Entry rule entryRuleEmptyProcess
entryRuleEmptyProcess returns [String current=null]:
	{ newCompositeNode(grammarAccess.getEmptyProcessRule()); }
	iv_ruleEmptyProcess=ruleEmptyProcess
	{ $current=$iv_ruleEmptyProcess.current.getText(); }
	EOF;

// Rule EmptyProcess
ruleEmptyProcess returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		kw='empty'
		{
			$current.merge(kw);
			newLeafNode(kw, grammarAccess.getEmptyProcessAccess().getEmptyKeyword_0());
		}
		kw='process'
		{
			$current.merge(kw);
			newLeafNode(kw, grammarAccess.getEmptyProcessAccess().getProcessKeyword_1());
		}
	)
;

// Entry rule entryRuleCompoundProcess
entryRuleCompoundProcess returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getCompoundProcessRule()); }
	iv_ruleCompoundProcess=ruleCompoundProcess
	{ $current=$iv_ruleCompoundProcess.current; }
	EOF;

// Rule CompoundProcess
ruleCompoundProcess returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='compound'
		{
			newLeafNode(otherlv_0, grammarAccess.getCompoundProcessAccess().getCompoundKeyword_0());
		}
		otherlv_1='process'
		{
			newLeafNode(otherlv_1, grammarAccess.getCompoundProcessAccess().getProcessKeyword_1());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getCompoundProcessAccess().getTaskTaskParserRuleCall_2_0());
				}
				lv_task_2_0=ruleTask
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getCompoundProcessRule());
					}
					add(
						$current,
						"task",
						lv_task_2_0,
						"org.xtext.example.bilang.Bilang.Task");
					afterParserOrEnumRuleCall();
				}
			)
		)+
	)
;

// Entry rule entryRuleAbstractProcess
entryRuleAbstractProcess returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getAbstractProcessRule()); }
	iv_ruleAbstractProcess=ruleAbstractProcess
	{ $current=$iv_ruleAbstractProcess.current; }
	EOF;

// Rule AbstractProcess
ruleAbstractProcess returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='abstract'
		{
			newLeafNode(otherlv_0, grammarAccess.getAbstractProcessAccess().getAbstractKeyword_0());
		}
		otherlv_1='process'
		{
			newLeafNode(otherlv_1, grammarAccess.getAbstractProcessAccess().getProcessKeyword_1());
		}
		otherlv_2='with'
		{
			newLeafNode(otherlv_2, grammarAccess.getAbstractProcessAccess().getWithKeyword_2());
		}
		otherlv_3='name'
		{
			newLeafNode(otherlv_3, grammarAccess.getAbstractProcessAccess().getNameKeyword_3());
		}
		(
			(
				lv_name_4_0=RULE_ID
				{
					newLeafNode(lv_name_4_0, grammarAccess.getAbstractProcessAccess().getNameIDTerminalRuleCall_4_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getAbstractProcessRule());
					}
					setWithLastConsumed(
						$current,
						"name",
						lv_name_4_0,
						"org.eclipse.xtext.common.Terminals.ID");
				}
			)
		)
		otherlv_5='and'
		{
			newLeafNode(otherlv_5, grammarAccess.getAbstractProcessAccess().getAndKeyword_5());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getAbstractProcessAccess().getParamValuesParamValueParserRuleCall_6_0());
				}
				lv_paramValues_6_0=ruleParamValue
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getAbstractProcessRule());
					}
					add(
						$current,
						"paramValues",
						lv_paramValues_6_0,
						"org.xtext.example.bilang.Bilang.ParamValue");
					afterParserOrEnumRuleCall();
				}
			)
		)+
	)
;

// Entry rule entryRuleParamValue
entryRuleParamValue returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getParamValueRule()); }
	iv_ruleParamValue=ruleParamValue
	{ $current=$iv_ruleParamValue.current; }
	EOF;

// Rule ParamValue
ruleParamValue returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='parameter'
		{
			newLeafNode(otherlv_0, grammarAccess.getParamValueAccess().getParameterKeyword_0());
		}
		(
			(
				lv_param_1_0=RULE_ID
				{
					newLeafNode(lv_param_1_0, grammarAccess.getParamValueAccess().getParamIDTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getParamValueRule());
					}
					setWithLastConsumed(
						$current,
						"param",
						lv_param_1_0,
						"org.eclipse.xtext.common.Terminals.ID");
				}
			)
		)
		otherlv_2='and'
		{
			newLeafNode(otherlv_2, grammarAccess.getParamValueAccess().getAndKeyword_2());
		}
		otherlv_3='value'
		{
			newLeafNode(otherlv_3, grammarAccess.getParamValueAccess().getValueKeyword_3());
		}
		(
			(
				lv_value_4_0=RULE_ID
				{
					newLeafNode(lv_value_4_0, grammarAccess.getParamValueAccess().getValueIDTerminalRuleCall_4_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getParamValueRule());
					}
					setWithLastConsumed(
						$current,
						"value",
						lv_value_4_0,
						"org.eclipse.xtext.common.Terminals.ID");
				}
			)
		)
	)
;

// Entry rule entryRuleRetrieveTask
entryRuleRetrieveTask returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getRetrieveTaskRule()); }
	iv_ruleRetrieveTask=ruleRetrieveTask
	{ $current=$iv_ruleRetrieveTask.current; }
	EOF;

// Rule RetrieveTask
ruleRetrieveTask returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		{
			newCompositeNode(grammarAccess.getRetrieveTaskAccess().getRetrieveDocumentParserRuleCall_0());
		}
		this_RetrieveDocument_0=ruleRetrieveDocument
		{
			$current = $this_RetrieveDocument_0.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getRetrieveTaskAccess().getRetrieveFullAddressParserRuleCall_1());
		}
		this_RetrieveFullAddress_1=ruleRetrieveFullAddress
		{
			$current = $this_RetrieveFullAddress_1.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getRetrieveTaskAccess().getRetrievePersonsParserRuleCall_2());
		}
		this_RetrievePersons_2=ruleRetrievePersons
		{
			$current = $this_RetrievePersons_2.current;
			afterParserOrEnumRuleCall();
		}
	)
;

// Entry rule entryRuleSendTask
entryRuleSendTask returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getSendTaskRule()); }
	iv_ruleSendTask=ruleSendTask
	{ $current=$iv_ruleSendTask.current; }
	EOF;

// Rule SendTask
ruleSendTask returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		{
			newCompositeNode(grammarAccess.getSendTaskAccess().getSendEmailParserRuleCall_0());
		}
		this_SendEmail_0=ruleSendEmail
		{
			$current = $this_SendEmail_0.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getSendTaskAccess().getSendSMSParserRuleCall_1());
		}
		this_SendSMS_1=ruleSendSMS
		{
			$current = $this_SendSMS_1.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getSendTaskAccess().getSendSnailMailParserRuleCall_2());
		}
		this_SendSnailMail_2=ruleSendSnailMail
		{
			$current = $this_SendSnailMail_2.current;
			afterParserOrEnumRuleCall();
		}
	)
;

// Entry rule entryRulePersonTask
entryRulePersonTask returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getPersonTaskRule()); }
	iv_rulePersonTask=rulePersonTask
	{ $current=$iv_rulePersonTask.current; }
	EOF;

// Rule PersonTask
rulePersonTask returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		{
			newCompositeNode(grammarAccess.getPersonTaskAccess().getCallPersonParserRuleCall_0());
		}
		this_CallPerson_0=ruleCallPerson
		{
			$current = $this_CallPerson_0.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getPersonTaskAccess().getAddPersonParserRuleCall_1());
		}
		this_AddPerson_1=ruleAddPerson
		{
			$current = $this_AddPerson_1.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getPersonTaskAccess().getDeletePersonParserRuleCall_2());
		}
		this_DeletePerson_2=ruleDeletePerson
		{
			$current = $this_DeletePerson_2.current;
			afterParserOrEnumRuleCall();
		}
	)
;

// Entry rule entryRuleSendEmail
entryRuleSendEmail returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getSendEmailRule()); }
	iv_ruleSendEmail=ruleSendEmail
	{ $current=$iv_ruleSendEmail.current; }
	EOF;

// Rule SendEmail
ruleSendEmail returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='send'
		{
			newLeafNode(otherlv_0, grammarAccess.getSendEmailAccess().getSendKeyword_0());
		}
		otherlv_1='an'
		{
			newLeafNode(otherlv_1, grammarAccess.getSendEmailAccess().getAnKeyword_1());
		}
		otherlv_2='email'
		{
			newLeafNode(otherlv_2, grammarAccess.getSendEmailAccess().getEmailKeyword_2());
		}
		otherlv_3='to'
		{
			newLeafNode(otherlv_3, grammarAccess.getSendEmailAccess().getToKeyword_3());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getSendEmailAccess().getPersonPersonParserRuleCall_4_0());
				}
				lv_person_4_0=rulePerson
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getSendEmailRule());
					}
					add(
						$current,
						"person",
						lv_person_4_0,
						"org.xtext.example.bilang.Bilang.Person");
					afterParserOrEnumRuleCall();
				}
			)
		)+
		otherlv_5='with'
		{
			newLeafNode(otherlv_5, grammarAccess.getSendEmailAccess().getWithKeyword_5());
		}
		otherlv_6='content'
		{
			newLeafNode(otherlv_6, grammarAccess.getSendEmailAccess().getContentKeyword_6());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getSendEmailAccess().getContentContentParserRuleCall_7_0());
				}
				lv_content_7_0=ruleContent
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getSendEmailRule());
					}
					set(
						$current,
						"content",
						lv_content_7_0,
						"org.xtext.example.bilang.Bilang.Content");
					afterParserOrEnumRuleCall();
				}
			)
		)
	)
;

// Entry rule entryRuleSendSMS
entryRuleSendSMS returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getSendSMSRule()); }
	iv_ruleSendSMS=ruleSendSMS
	{ $current=$iv_ruleSendSMS.current; }
	EOF;

// Rule SendSMS
ruleSendSMS returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='send'
		{
			newLeafNode(otherlv_0, grammarAccess.getSendSMSAccess().getSendKeyword_0());
		}
		otherlv_1='an'
		{
			newLeafNode(otherlv_1, grammarAccess.getSendSMSAccess().getAnKeyword_1());
		}
		otherlv_2='sms'
		{
			newLeafNode(otherlv_2, grammarAccess.getSendSMSAccess().getSmsKeyword_2());
		}
		otherlv_3='to'
		{
			newLeafNode(otherlv_3, grammarAccess.getSendSMSAccess().getToKeyword_3());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getSendSMSAccess().getPersonPersonParserRuleCall_4_0());
				}
				lv_person_4_0=rulePerson
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getSendSMSRule());
					}
					add(
						$current,
						"person",
						lv_person_4_0,
						"org.xtext.example.bilang.Bilang.Person");
					afterParserOrEnumRuleCall();
				}
			)
		)+
		otherlv_5='with'
		{
			newLeafNode(otherlv_5, grammarAccess.getSendSMSAccess().getWithKeyword_5());
		}
		otherlv_6='content'
		{
			newLeafNode(otherlv_6, grammarAccess.getSendSMSAccess().getContentKeyword_6());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getSendSMSAccess().getContentContentParserRuleCall_7_0());
				}
				lv_content_7_0=ruleContent
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getSendSMSRule());
					}
					set(
						$current,
						"content",
						lv_content_7_0,
						"org.xtext.example.bilang.Bilang.Content");
					afterParserOrEnumRuleCall();
				}
			)
		)
	)
;

// Entry rule entryRuleSendSnailMail
entryRuleSendSnailMail returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getSendSnailMailRule()); }
	iv_ruleSendSnailMail=ruleSendSnailMail
	{ $current=$iv_ruleSendSnailMail.current; }
	EOF;

// Rule SendSnailMail
ruleSendSnailMail returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='send'
		{
			newLeafNode(otherlv_0, grammarAccess.getSendSnailMailAccess().getSendKeyword_0());
		}
		otherlv_1='a'
		{
			newLeafNode(otherlv_1, grammarAccess.getSendSnailMailAccess().getAKeyword_1());
		}
		otherlv_2='snail'
		{
			newLeafNode(otherlv_2, grammarAccess.getSendSnailMailAccess().getSnailKeyword_2());
		}
		otherlv_3='mail'
		{
			newLeafNode(otherlv_3, grammarAccess.getSendSnailMailAccess().getMailKeyword_3());
		}
		otherlv_4='to'
		{
			newLeafNode(otherlv_4, grammarAccess.getSendSnailMailAccess().getToKeyword_4());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getSendSnailMailAccess().getPersonPersonParserRuleCall_5_0());
				}
				lv_person_5_0=rulePerson
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getSendSnailMailRule());
					}
					add(
						$current,
						"person",
						lv_person_5_0,
						"org.xtext.example.bilang.Bilang.Person");
					afterParserOrEnumRuleCall();
				}
			)
		)+
		otherlv_6='with'
		{
			newLeafNode(otherlv_6, grammarAccess.getSendSnailMailAccess().getWithKeyword_6());
		}
		otherlv_7='content'
		{
			newLeafNode(otherlv_7, grammarAccess.getSendSnailMailAccess().getContentKeyword_7());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getSendSnailMailAccess().getContentContentParserRuleCall_8_0());
				}
				lv_content_8_0=ruleContent
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getSendSnailMailRule());
					}
					set(
						$current,
						"content",
						lv_content_8_0,
						"org.xtext.example.bilang.Bilang.Content");
					afterParserOrEnumRuleCall();
				}
			)
		)
	)
;

// Entry rule entryRuleRetrieveDocument
entryRuleRetrieveDocument returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getRetrieveDocumentRule()); }
	iv_ruleRetrieveDocument=ruleRetrieveDocument
	{ $current=$iv_ruleRetrieveDocument.current; }
	EOF;

// Rule RetrieveDocument
ruleRetrieveDocument returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='retrieve'
		{
			newLeafNode(otherlv_0, grammarAccess.getRetrieveDocumentAccess().getRetrieveKeyword_0());
		}
		otherlv_1='document'
		{
			newLeafNode(otherlv_1, grammarAccess.getRetrieveDocumentAccess().getDocumentKeyword_1());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getRetrieveDocumentAccess().getDocumentDocumentParserRuleCall_2_0());
				}
				lv_document_2_0=ruleDocument
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getRetrieveDocumentRule());
					}
					set(
						$current,
						"document",
						lv_document_2_0,
						"org.xtext.example.bilang.Bilang.Document");
					afterParserOrEnumRuleCall();
				}
			)
		)
	)
;

// Entry rule entryRuleRetrieveFullAddress
entryRuleRetrieveFullAddress returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getRetrieveFullAddressRule()); }
	iv_ruleRetrieveFullAddress=ruleRetrieveFullAddress
	{ $current=$iv_ruleRetrieveFullAddress.current; }
	EOF;

// Rule RetrieveFullAddress
ruleRetrieveFullAddress returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='retrieve'
		{
			newLeafNode(otherlv_0, grammarAccess.getRetrieveFullAddressAccess().getRetrieveKeyword_0());
		}
		otherlv_1='full'
		{
			newLeafNode(otherlv_1, grammarAccess.getRetrieveFullAddressAccess().getFullKeyword_1());
		}
		otherlv_2='address'
		{
			newLeafNode(otherlv_2, grammarAccess.getRetrieveFullAddressAccess().getAddressKeyword_2());
		}
		otherlv_3='of'
		{
			newLeafNode(otherlv_3, grammarAccess.getRetrieveFullAddressAccess().getOfKeyword_3());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getRetrieveFullAddressAccess().getPersonAdressPersonByAddressParserRuleCall_4_0());
				}
				lv_personAdress_4_0=rulePersonByAddress
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getRetrieveFullAddressRule());
					}
					set(
						$current,
						"personAdress",
						lv_personAdress_4_0,
						"org.xtext.example.bilang.Bilang.PersonByAddress");
					afterParserOrEnumRuleCall();
				}
			)
		)
	)
;

// Entry rule entryRuleRetrievePersons
entryRuleRetrievePersons returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getRetrievePersonsRule()); }
	iv_ruleRetrievePersons=ruleRetrievePersons
	{ $current=$iv_ruleRetrievePersons.current; }
	EOF;

// Rule RetrievePersons
ruleRetrievePersons returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='retrieve'
		{
			newLeafNode(otherlv_0, grammarAccess.getRetrievePersonsAccess().getRetrieveKeyword_0());
		}
		otherlv_1='persons'
		{
			newLeafNode(otherlv_1, grammarAccess.getRetrievePersonsAccess().getPersonsKeyword_1());
		}
		otherlv_2='with'
		{
			newLeafNode(otherlv_2, grammarAccess.getRetrievePersonsAccess().getWithKeyword_2());
		}
		otherlv_3='search'
		{
			newLeafNode(otherlv_3, grammarAccess.getRetrievePersonsAccess().getSearchKeyword_3());
		}
		(
			(
				lv_personSearch_4_0=RULE_ID
				{
					newLeafNode(lv_personSearch_4_0, grammarAccess.getRetrievePersonsAccess().getPersonSearchIDTerminalRuleCall_4_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getRetrievePersonsRule());
					}
					setWithLastConsumed(
						$current,
						"personSearch",
						lv_personSearch_4_0,
						"org.eclipse.xtext.common.Terminals.ID");
				}
			)
		)
	)
;

// Entry rule entryRuleCallPerson
entryRuleCallPerson returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getCallPersonRule()); }
	iv_ruleCallPerson=ruleCallPerson
	{ $current=$iv_ruleCallPerson.current; }
	EOF;

// Rule CallPerson
ruleCallPerson returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='phone'
		{
			newLeafNode(otherlv_0, grammarAccess.getCallPersonAccess().getPhoneKeyword_0());
		}
		otherlv_1='call'
		{
			newLeafNode(otherlv_1, grammarAccess.getCallPersonAccess().getCallKeyword_1());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getCallPersonAccess().getPersonPersonParserRuleCall_2_0());
				}
				lv_person_2_0=rulePerson
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getCallPersonRule());
					}
					set(
						$current,
						"person",
						lv_person_2_0,
						"org.xtext.example.bilang.Bilang.Person");
					afterParserOrEnumRuleCall();
				}
			)
		)
	)
;

// Entry rule entryRuleAddPerson
entryRuleAddPerson returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getAddPersonRule()); }
	iv_ruleAddPerson=ruleAddPerson
	{ $current=$iv_ruleAddPerson.current; }
	EOF;

// Rule AddPerson
ruleAddPerson returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='add'
		{
			newLeafNode(otherlv_0, grammarAccess.getAddPersonAccess().getAddKeyword_0());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getAddPersonAccess().getAliasPersonByAliasParserRuleCall_1_0());
				}
				lv_alias_1_0=rulePersonByAlias
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getAddPersonRule());
					}
					set(
						$current,
						"alias",
						lv_alias_1_0,
						"org.xtext.example.bilang.Bilang.PersonByAlias");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_2='and'
			{
				newLeafNode(otherlv_2, grammarAccess.getAddPersonAccess().getAndKeyword_2_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getAddPersonAccess().getPersonPersonParserRuleCall_2_1_0());
					}
					lv_person_3_0=rulePerson
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getAddPersonRule());
						}
						add(
							$current,
							"person",
							lv_person_3_0,
							"org.xtext.example.bilang.Bilang.Person");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)+
	)
;

// Entry rule entryRuleDeletePerson
entryRuleDeletePerson returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getDeletePersonRule()); }
	iv_ruleDeletePerson=ruleDeletePerson
	{ $current=$iv_ruleDeletePerson.current; }
	EOF;

// Rule DeletePerson
ruleDeletePerson returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='delete'
		{
			newLeafNode(otherlv_0, grammarAccess.getDeletePersonAccess().getDeleteKeyword_0());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getDeletePersonAccess().getAliasPersonByAliasParserRuleCall_1_0());
				}
				lv_alias_1_0=rulePersonByAlias
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getDeletePersonRule());
					}
					set(
						$current,
						"alias",
						lv_alias_1_0,
						"org.xtext.example.bilang.Bilang.PersonByAlias");
					afterParserOrEnumRuleCall();
				}
			)
		)
	)
;

// Entry rule entryRulePerson
entryRulePerson returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getPersonRule()); }
	iv_rulePerson=rulePerson
	{ $current=$iv_rulePerson.current; }
	EOF;

// Rule Person
rulePerson returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		{
			newCompositeNode(grammarAccess.getPersonAccess().getPersonByEmailParserRuleCall_0());
		}
		this_PersonByEmail_0=rulePersonByEmail
		{
			$current = $this_PersonByEmail_0.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getPersonAccess().getPersonByAliasParserRuleCall_1());
		}
		this_PersonByAlias_1=rulePersonByAlias
		{
			$current = $this_PersonByAlias_1.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getPersonAccess().getPersonByNameParserRuleCall_2());
		}
		this_PersonByName_2=rulePersonByName
		{
			$current = $this_PersonByName_2.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getPersonAccess().getPersonByPhoneParserRuleCall_3());
		}
		this_PersonByPhone_3=rulePersonByPhone
		{
			$current = $this_PersonByPhone_3.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getPersonAccess().getPersonByAddressParserRuleCall_4());
		}
		this_PersonByAddress_4=rulePersonByAddress
		{
			$current = $this_PersonByAddress_4.current;
			afterParserOrEnumRuleCall();
		}
	)
;

// Entry rule entryRulePersonByEmail
entryRulePersonByEmail returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getPersonByEmailRule()); }
	iv_rulePersonByEmail=rulePersonByEmail
	{ $current=$iv_rulePersonByEmail.current; }
	EOF;

// Rule PersonByEmail
rulePersonByEmail returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='person'
		{
			newLeafNode(otherlv_0, grammarAccess.getPersonByEmailAccess().getPersonKeyword_0());
		}
		otherlv_1='with'
		{
			newLeafNode(otherlv_1, grammarAccess.getPersonByEmailAccess().getWithKeyword_1());
		}
		otherlv_2='email'
		{
			newLeafNode(otherlv_2, grammarAccess.getPersonByEmailAccess().getEmailKeyword_2());
		}
		(
			(
				lv_emailaddress_3_0=RULE_EMAIL_ADDRESS
				{
					newLeafNode(lv_emailaddress_3_0, grammarAccess.getPersonByEmailAccess().getEmailaddressEMAIL_ADDRESSTerminalRuleCall_3_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getPersonByEmailRule());
					}
					setWithLastConsumed(
						$current,
						"emailaddress",
						lv_emailaddress_3_0,
						"org.xtext.example.bilang.Bilang.EMAIL_ADDRESS");
				}
			)
		)
	)
;

// Entry rule entryRulePersonByAlias
entryRulePersonByAlias returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getPersonByAliasRule()); }
	iv_rulePersonByAlias=rulePersonByAlias
	{ $current=$iv_rulePersonByAlias.current; }
	EOF;

// Rule PersonByAlias
rulePersonByAlias returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='person'
		{
			newLeafNode(otherlv_0, grammarAccess.getPersonByAliasAccess().getPersonKeyword_0());
		}
		otherlv_1='with'
		{
			newLeafNode(otherlv_1, grammarAccess.getPersonByAliasAccess().getWithKeyword_1());
		}
		otherlv_2='alias'
		{
			newLeafNode(otherlv_2, grammarAccess.getPersonByAliasAccess().getAliasKeyword_2());
		}
		(
			(
				lv_alias_3_0=RULE_ID
				{
					newLeafNode(lv_alias_3_0, grammarAccess.getPersonByAliasAccess().getAliasIDTerminalRuleCall_3_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getPersonByAliasRule());
					}
					setWithLastConsumed(
						$current,
						"alias",
						lv_alias_3_0,
						"org.eclipse.xtext.common.Terminals.ID");
				}
			)
		)
	)
;

// Entry rule entryRulePersonByName
entryRulePersonByName returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getPersonByNameRule()); }
	iv_rulePersonByName=rulePersonByName
	{ $current=$iv_rulePersonByName.current; }
	EOF;

// Rule PersonByName
rulePersonByName returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='person'
		{
			newLeafNode(otherlv_0, grammarAccess.getPersonByNameAccess().getPersonKeyword_0());
		}
		otherlv_1='with'
		{
			newLeafNode(otherlv_1, grammarAccess.getPersonByNameAccess().getWithKeyword_1());
		}
		otherlv_2='first'
		{
			newLeafNode(otherlv_2, grammarAccess.getPersonByNameAccess().getFirstKeyword_2());
		}
		otherlv_3='name'
		{
			newLeafNode(otherlv_3, grammarAccess.getPersonByNameAccess().getNameKeyword_3());
		}
		(
			(
				lv_firstName_4_0=RULE_ID
				{
					newLeafNode(lv_firstName_4_0, grammarAccess.getPersonByNameAccess().getFirstNameIDTerminalRuleCall_4_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getPersonByNameRule());
					}
					setWithLastConsumed(
						$current,
						"firstName",
						lv_firstName_4_0,
						"org.eclipse.xtext.common.Terminals.ID");
				}
			)
		)
		otherlv_5='and'
		{
			newLeafNode(otherlv_5, grammarAccess.getPersonByNameAccess().getAndKeyword_5());
		}
		otherlv_6='last'
		{
			newLeafNode(otherlv_6, grammarAccess.getPersonByNameAccess().getLastKeyword_6());
		}
		otherlv_7='name'
		{
			newLeafNode(otherlv_7, grammarAccess.getPersonByNameAccess().getNameKeyword_7());
		}
		(
			(
				lv_lastName_8_0=RULE_STRING
				{
					newLeafNode(lv_lastName_8_0, grammarAccess.getPersonByNameAccess().getLastNameSTRINGTerminalRuleCall_8_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getPersonByNameRule());
					}
					setWithLastConsumed(
						$current,
						"lastName",
						lv_lastName_8_0,
						"org.eclipse.xtext.common.Terminals.STRING");
				}
			)
		)
	)
;

// Entry rule entryRulePersonByPhone
entryRulePersonByPhone returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getPersonByPhoneRule()); }
	iv_rulePersonByPhone=rulePersonByPhone
	{ $current=$iv_rulePersonByPhone.current; }
	EOF;

// Rule PersonByPhone
rulePersonByPhone returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='person'
		{
			newLeafNode(otherlv_0, grammarAccess.getPersonByPhoneAccess().getPersonKeyword_0());
		}
		otherlv_1='with'
		{
			newLeafNode(otherlv_1, grammarAccess.getPersonByPhoneAccess().getWithKeyword_1());
		}
		otherlv_2='phone'
		{
			newLeafNode(otherlv_2, grammarAccess.getPersonByPhoneAccess().getPhoneKeyword_2());
		}
		otherlv_3='number'
		{
			newLeafNode(otherlv_3, grammarAccess.getPersonByPhoneAccess().getNumberKeyword_3());
		}
		(
			(
				lv_phone_4_0=RULE_PHONE_NUMBER
				{
					newLeafNode(lv_phone_4_0, grammarAccess.getPersonByPhoneAccess().getPhonePHONE_NUMBERTerminalRuleCall_4_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getPersonByPhoneRule());
					}
					setWithLastConsumed(
						$current,
						"phone",
						lv_phone_4_0,
						"org.xtext.example.bilang.Bilang.PHONE_NUMBER");
				}
			)
		)
	)
;

// Entry rule entryRulePersonByAddress
entryRulePersonByAddress returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getPersonByAddressRule()); }
	iv_rulePersonByAddress=rulePersonByAddress
	{ $current=$iv_rulePersonByAddress.current; }
	EOF;

// Rule PersonByAddress
rulePersonByAddress returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='person'
		{
			newLeafNode(otherlv_0, grammarAccess.getPersonByAddressAccess().getPersonKeyword_0());
		}
		otherlv_1='with'
		{
			newLeafNode(otherlv_1, grammarAccess.getPersonByAddressAccess().getWithKeyword_1());
		}
		otherlv_2='zip'
		{
			newLeafNode(otherlv_2, grammarAccess.getPersonByAddressAccess().getZipKeyword_2());
		}
		otherlv_3='code'
		{
			newLeafNode(otherlv_3, grammarAccess.getPersonByAddressAccess().getCodeKeyword_3());
		}
		(
			(
				lv_zipcode_4_0=RULE_DUTCH_POSTCODE
				{
					newLeafNode(lv_zipcode_4_0, grammarAccess.getPersonByAddressAccess().getZipcodeDUTCH_POSTCODETerminalRuleCall_4_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getPersonByAddressRule());
					}
					setWithLastConsumed(
						$current,
						"zipcode",
						lv_zipcode_4_0,
						"org.xtext.example.bilang.Bilang.DUTCH_POSTCODE");
				}
			)
		)
		otherlv_5='and'
		{
			newLeafNode(otherlv_5, grammarAccess.getPersonByAddressAccess().getAndKeyword_5());
		}
		otherlv_6='house'
		{
			newLeafNode(otherlv_6, grammarAccess.getPersonByAddressAccess().getHouseKeyword_6());
		}
		otherlv_7='number'
		{
			newLeafNode(otherlv_7, grammarAccess.getPersonByAddressAccess().getNumberKeyword_7());
		}
		(
			(
				lv_housenumber_8_0=RULE_HOUSENUMBER
				{
					newLeafNode(lv_housenumber_8_0, grammarAccess.getPersonByAddressAccess().getHousenumberHOUSENUMBERTerminalRuleCall_8_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getPersonByAddressRule());
					}
					setWithLastConsumed(
						$current,
						"housenumber",
						lv_housenumber_8_0,
						"org.xtext.example.bilang.Bilang.HOUSENUMBER");
				}
			)
		)
	)
;

// Entry rule entryRuleContent
entryRuleContent returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getContentRule()); }
	iv_ruleContent=ruleContent
	{ $current=$iv_ruleContent.current; }
	EOF;

// Rule Content
ruleContent returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		{
			newCompositeNode(grammarAccess.getContentAccess().getMessageParserRuleCall_0());
		}
		this_Message_0=ruleMessage
		{
			$current = $this_Message_0.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getContentAccess().getDocumentParserRuleCall_1());
		}
		this_Document_1=ruleDocument
		{
			$current = $this_Document_1.current;
			afterParserOrEnumRuleCall();
		}
	)
;

// Entry rule entryRuleMessage
entryRuleMessage returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getMessageRule()); }
	iv_ruleMessage=ruleMessage
	{ $current=$iv_ruleMessage.current; }
	EOF;

// Rule Message
ruleMessage returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='message'
		{
			newLeafNode(otherlv_0, grammarAccess.getMessageAccess().getMessageKeyword_0());
		}
		(
			(
				lv_message_1_0=RULE_STRING
				{
					newLeafNode(lv_message_1_0, grammarAccess.getMessageAccess().getMessageSTRINGTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getMessageRule());
					}
					setWithLastConsumed(
						$current,
						"message",
						lv_message_1_0,
						"org.eclipse.xtext.common.Terminals.STRING");
				}
			)
		)
	)
;

// Entry rule entryRuleDocument
entryRuleDocument returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getDocumentRule()); }
	iv_ruleDocument=ruleDocument
	{ $current=$iv_ruleDocument.current; }
	EOF;

// Rule Document
ruleDocument returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		{
			newCompositeNode(grammarAccess.getDocumentAccess().getInvoiceParserRuleCall_0());
		}
		this_Invoice_0=ruleInvoice
		{
			$current = $this_Invoice_0.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getDocumentAccess().getDocumentPersonParserRuleCall_1());
		}
		this_DocumentPerson_1=ruleDocumentPerson
		{
			$current = $this_DocumentPerson_1.current;
			afterParserOrEnumRuleCall();
		}
	)
;

// Entry rule entryRuleInvoice
entryRuleInvoice returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getInvoiceRule()); }
	iv_ruleInvoice=ruleInvoice
	{ $current=$iv_ruleInvoice.current; }
	EOF;

// Rule Invoice
ruleInvoice returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='invoice'
		{
			newLeafNode(otherlv_0, grammarAccess.getInvoiceAccess().getInvoiceKeyword_0());
		}
		otherlv_1='with'
		{
			newLeafNode(otherlv_1, grammarAccess.getInvoiceAccess().getWithKeyword_1());
		}
		otherlv_2='code'
		{
			newLeafNode(otherlv_2, grammarAccess.getInvoiceAccess().getCodeKeyword_2());
		}
		(
			(
				lv_code_3_0=RULE_INT
				{
					newLeafNode(lv_code_3_0, grammarAccess.getInvoiceAccess().getCodeINTTerminalRuleCall_3_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getInvoiceRule());
					}
					setWithLastConsumed(
						$current,
						"code",
						lv_code_3_0,
						"org.eclipse.xtext.common.Terminals.INT");
				}
			)
		)
	)
;

// Entry rule entryRuleDocumentPerson
entryRuleDocumentPerson returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getDocumentPersonRule()); }
	iv_ruleDocumentPerson=ruleDocumentPerson
	{ $current=$iv_ruleDocumentPerson.current; }
	EOF;

// Rule DocumentPerson
ruleDocumentPerson returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='information'
		{
			newLeafNode(otherlv_0, grammarAccess.getDocumentPersonAccess().getInformationKeyword_0());
		}
		otherlv_1='about'
		{
			newLeafNode(otherlv_1, grammarAccess.getDocumentPersonAccess().getAboutKeyword_1());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getDocumentPersonAccess().getPersonPersonParserRuleCall_2_0());
				}
				lv_person_2_0=rulePerson
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getDocumentPersonRule());
					}
					set(
						$current,
						"person",
						lv_person_2_0,
						"org.xtext.example.bilang.Bilang.Person");
					afterParserOrEnumRuleCall();
				}
			)
		)
	)
;

RULE_EMAIL_ADDRESS : ('a'..'z'|'A'..'Z'|'0'..'9'|'_'|'-'|'.')+ '@' ('a'..'z'|'A'..'Z'|'0'..'9'|'-'|'.')+;

RULE_PHONE_NUMBER : '+' ('0'..'9')+;

RULE_HOUSENUMBER : ('0'..'9')+ ('a'..'z'|'A'..'Z')?;

RULE_DUTCH_POSTCODE : '0'..'9' '0'..'9' '0'..'9' '0'..'9' ' '? 'A'..'Z' 'A'..'Z';

RULE_ID : '^'? ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

RULE_INT : ('0'..'9')+;

RULE_STRING : ('"' ('\\' .|~(('\\'|'"')))* '"'|'\'' ('\\' .|~(('\\'|'\'')))* '\'');

RULE_ML_COMMENT : '/*' ( options {greedy=false;} : . )*'*/';

RULE_SL_COMMENT : '//' ~(('\n'|'\r'))* ('\r'? '\n')?;

RULE_WS : (' '|'\t'|'\r'|'\n')+;

RULE_ANY_OTHER : .;
