/*
 * generated by Xtext 2.44.0
 */
package org.xtext.example.bilang.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class BilangUiModule extends AbstractBilangUiModule {

	public BilangUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
