/**
 * generated by Xtext 2.44.0
 */
package org.xtext.example.bilang.bilang.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.xtext.example.bilang.bilang.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class BilangFactoryImpl extends EFactoryImpl implements BilangFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static BilangFactory init()
  {
    try
    {
      BilangFactory theBilangFactory = (BilangFactory)EPackage.Registry.INSTANCE.getEFactory(BilangPackage.eNS_URI);
      if (theBilangFactory != null)
      {
        return theBilangFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new BilangFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BilangFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case BilangPackage.MODEL: return createModel();
      case BilangPackage.TASK: return createTask();
      case BilangPackage.COMPOUND_PROCESS: return createCompoundProcess();
      case BilangPackage.ABSTRACT_PROCESS: return createAbstractProcess();
      case BilangPackage.PARAM_VALUE: return createParamValue();
      case BilangPackage.RETRIEVE_TASK: return createRetrieveTask();
      case BilangPackage.SEND_TASK: return createSendTask();
      case BilangPackage.PERSON_TASK: return createPersonTask();
      case BilangPackage.SEND_EMAIL: return createSendEmail();
      case BilangPackage.SEND_SMS: return createSendSMS();
      case BilangPackage.SEND_SNAIL_MAIL: return createSendSnailMail();
      case BilangPackage.RETRIEVE_DOCUMENT: return createRetrieveDocument();
      case BilangPackage.RETRIEVE_FULL_ADDRESS: return createRetrieveFullAddress();
      case BilangPackage.RETRIEVE_PERSONS: return createRetrievePersons();
      case BilangPackage.CALL_PERSON: return createCallPerson();
      case BilangPackage.ADD_PERSON: return createAddPerson();
      case BilangPackage.DELETE_PERSON: return createDeletePerson();
      case BilangPackage.PERSON: return createPerson();
      case BilangPackage.PERSON_BY_EMAIL: return createPersonByEmail();
      case BilangPackage.PERSON_BY_ALIAS: return createPersonByAlias();
      case BilangPackage.PERSON_BY_NAME: return createPersonByName();
      case BilangPackage.PERSON_BY_PHONE: return createPersonByPhone();
      case BilangPackage.PERSON_BY_ADDRESS: return createPersonByAddress();
      case BilangPackage.CONTENT: return createContent();
      case BilangPackage.MESSAGE: return createMessage();
      case BilangPackage.DOCUMENT: return createDocument();
      case BilangPackage.INVOICE: return createInvoice();
      case BilangPackage.DOCUMENT_PERSON: return createDocumentPerson();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Model createModel()
  {
    ModelImpl model = new ModelImpl();
    return model;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Task createTask()
  {
    TaskImpl task = new TaskImpl();
    return task;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CompoundProcess createCompoundProcess()
  {
    CompoundProcessImpl compoundProcess = new CompoundProcessImpl();
    return compoundProcess;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AbstractProcess createAbstractProcess()
  {
    AbstractProcessImpl abstractProcess = new AbstractProcessImpl();
    return abstractProcess;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ParamValue createParamValue()
  {
    ParamValueImpl paramValue = new ParamValueImpl();
    return paramValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RetrieveTask createRetrieveTask()
  {
    RetrieveTaskImpl retrieveTask = new RetrieveTaskImpl();
    return retrieveTask;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SendTask createSendTask()
  {
    SendTaskImpl sendTask = new SendTaskImpl();
    return sendTask;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PersonTask createPersonTask()
  {
    PersonTaskImpl personTask = new PersonTaskImpl();
    return personTask;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SendEmail createSendEmail()
  {
    SendEmailImpl sendEmail = new SendEmailImpl();
    return sendEmail;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SendSMS createSendSMS()
  {
    SendSMSImpl sendSMS = new SendSMSImpl();
    return sendSMS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SendSnailMail createSendSnailMail()
  {
    SendSnailMailImpl sendSnailMail = new SendSnailMailImpl();
    return sendSnailMail;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RetrieveDocument createRetrieveDocument()
  {
    RetrieveDocumentImpl retrieveDocument = new RetrieveDocumentImpl();
    return retrieveDocument;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RetrieveFullAddress createRetrieveFullAddress()
  {
    RetrieveFullAddressImpl retrieveFullAddress = new RetrieveFullAddressImpl();
    return retrieveFullAddress;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RetrievePersons createRetrievePersons()
  {
    RetrievePersonsImpl retrievePersons = new RetrievePersonsImpl();
    return retrievePersons;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CallPerson createCallPerson()
  {
    CallPersonImpl callPerson = new CallPersonImpl();
    return callPerson;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AddPerson createAddPerson()
  {
    AddPersonImpl addPerson = new AddPersonImpl();
    return addPerson;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DeletePerson createDeletePerson()
  {
    DeletePersonImpl deletePerson = new DeletePersonImpl();
    return deletePerson;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Person createPerson()
  {
    PersonImpl person = new PersonImpl();
    return person;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PersonByEmail createPersonByEmail()
  {
    PersonByEmailImpl personByEmail = new PersonByEmailImpl();
    return personByEmail;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PersonByAlias createPersonByAlias()
  {
    PersonByAliasImpl personByAlias = new PersonByAliasImpl();
    return personByAlias;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PersonByName createPersonByName()
  {
    PersonByNameImpl personByName = new PersonByNameImpl();
    return personByName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PersonByPhone createPersonByPhone()
  {
    PersonByPhoneImpl personByPhone = new PersonByPhoneImpl();
    return personByPhone;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PersonByAddress createPersonByAddress()
  {
    PersonByAddressImpl personByAddress = new PersonByAddressImpl();
    return personByAddress;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Content createContent()
  {
    ContentImpl content = new ContentImpl();
    return content;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Message createMessage()
  {
    MessageImpl message = new MessageImpl();
    return message;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Document createDocument()
  {
    DocumentImpl document = new DocumentImpl();
    return document;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Invoice createInvoice()
  {
    InvoiceImpl invoice = new InvoiceImpl();
    return invoice;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DocumentPerson createDocumentPerson()
  {
    DocumentPersonImpl documentPerson = new DocumentPersonImpl();
    return documentPerson;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BilangPackage getBilangPackage()
  {
    return (BilangPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static BilangPackage getPackage()
  {
    return BilangPackage.eINSTANCE;
  }

} //BilangFactoryImpl
