/**
 * generated by Xtext 2.44.0
 */
package org.xtext.example.bilang.bilang.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.bilang.bilang.BilangPackage;
import org.xtext.example.bilang.bilang.PersonTask;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Person Task</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class PersonTaskImpl extends MinimalEObjectImpl.Container implements PersonTask
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PersonTaskImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BilangPackage.Literals.PERSON_TASK;
  }

} //PersonTaskImpl
