/**
 * generated by Xtext 2.44.0
 */
package org.xtext.example.bilang.bilang.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.bilang.bilang.BilangPackage;
import org.xtext.example.bilang.bilang.PersonByAddress;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Person By Address</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.bilang.bilang.impl.PersonByAddressImpl#getZipcode <em>Zipcode</em>}</li>
 *   <li>{@link org.xtext.example.bilang.bilang.impl.PersonByAddressImpl#getHousenumber <em>Housenumber</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PersonByAddressImpl extends PersonImpl implements PersonByAddress
{
  /**
   * The default value of the '{@link #getZipcode() <em>Zipcode</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getZipcode()
   * @generated
   * @ordered
   */
  protected static final String ZIPCODE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getZipcode() <em>Zipcode</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getZipcode()
   * @generated
   * @ordered
   */
  protected String zipcode = ZIPCODE_EDEFAULT;

  /**
   * The default value of the '{@link #getHousenumber() <em>Housenumber</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHousenumber()
   * @generated
   * @ordered
   */
  protected static final String HOUSENUMBER_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getHousenumber() <em>Housenumber</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHousenumber()
   * @generated
   * @ordered
   */
  protected String housenumber = HOUSENUMBER_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PersonByAddressImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BilangPackage.Literals.PERSON_BY_ADDRESS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getZipcode()
  {
    return zipcode;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setZipcode(String newZipcode)
  {
    String oldZipcode = zipcode;
    zipcode = newZipcode;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BilangPackage.PERSON_BY_ADDRESS__ZIPCODE, oldZipcode, zipcode));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getHousenumber()
  {
    return housenumber;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setHousenumber(String newHousenumber)
  {
    String oldHousenumber = housenumber;
    housenumber = newHousenumber;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BilangPackage.PERSON_BY_ADDRESS__HOUSENUMBER, oldHousenumber, housenumber));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case BilangPackage.PERSON_BY_ADDRESS__ZIPCODE:
        return getZipcode();
      case BilangPackage.PERSON_BY_ADDRESS__HOUSENUMBER:
        return getHousenumber();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case BilangPackage.PERSON_BY_ADDRESS__ZIPCODE:
        setZipcode((String)newValue);
        return;
      case BilangPackage.PERSON_BY_ADDRESS__HOUSENUMBER:
        setHousenumber((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case BilangPackage.PERSON_BY_ADDRESS__ZIPCODE:
        setZipcode(ZIPCODE_EDEFAULT);
        return;
      case BilangPackage.PERSON_BY_ADDRESS__HOUSENUMBER:
        setHousenumber(HOUSENUMBER_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case BilangPackage.PERSON_BY_ADDRESS__ZIPCODE:
        return ZIPCODE_EDEFAULT == null ? zipcode != null : !ZIPCODE_EDEFAULT.equals(zipcode);
      case BilangPackage.PERSON_BY_ADDRESS__HOUSENUMBER:
        return HOUSENUMBER_EDEFAULT == null ? housenumber != null : !HOUSENUMBER_EDEFAULT.equals(housenumber);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (zipcode: ");
    result.append(zipcode);
    result.append(", housenumber: ");
    result.append(housenumber);
    result.append(')');
    return result.toString();
  }

} //PersonByAddressImpl
