/**
 * generated by Xtext 2.44.0
 */
package org.xtext.example.bilang.bilang.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.bilang.bilang.BilangPackage;
import org.xtext.example.bilang.bilang.PersonByName;
import org.xtext.example.bilang.bilang.TextWithSpaces;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Person By Name</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.bilang.bilang.impl.PersonByNameImpl#getFirstName <em>First Name</em>}</li>
 *   <li>{@link org.xtext.example.bilang.bilang.impl.PersonByNameImpl#getLastName <em>Last Name</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PersonByNameImpl extends PersonImpl implements PersonByName
{
  /**
   * The default value of the '{@link #getFirstName() <em>First Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFirstName()
   * @generated
   * @ordered
   */
  protected static final String FIRST_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getFirstName() <em>First Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFirstName()
   * @generated
   * @ordered
   */
  protected String firstName = FIRST_NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getLastName() <em>Last Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLastName()
   * @generated
   * @ordered
   */
  protected TextWithSpaces lastName;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PersonByNameImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BilangPackage.Literals.PERSON_BY_NAME;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getFirstName()
  {
    return firstName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFirstName(String newFirstName)
  {
    String oldFirstName = firstName;
    firstName = newFirstName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BilangPackage.PERSON_BY_NAME__FIRST_NAME, oldFirstName, firstName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TextWithSpaces getLastName()
  {
    return lastName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetLastName(TextWithSpaces newLastName, NotificationChain msgs)
  {
    TextWithSpaces oldLastName = lastName;
    lastName = newLastName;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, BilangPackage.PERSON_BY_NAME__LAST_NAME, oldLastName, newLastName);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLastName(TextWithSpaces newLastName)
  {
    if (newLastName != lastName)
    {
      NotificationChain msgs = null;
      if (lastName != null)
        msgs = ((InternalEObject)lastName).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - BilangPackage.PERSON_BY_NAME__LAST_NAME, null, msgs);
      if (newLastName != null)
        msgs = ((InternalEObject)newLastName).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - BilangPackage.PERSON_BY_NAME__LAST_NAME, null, msgs);
      msgs = basicSetLastName(newLastName, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BilangPackage.PERSON_BY_NAME__LAST_NAME, newLastName, newLastName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case BilangPackage.PERSON_BY_NAME__LAST_NAME:
        return basicSetLastName(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case BilangPackage.PERSON_BY_NAME__FIRST_NAME:
        return getFirstName();
      case BilangPackage.PERSON_BY_NAME__LAST_NAME:
        return getLastName();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case BilangPackage.PERSON_BY_NAME__FIRST_NAME:
        setFirstName((String)newValue);
        return;
      case BilangPackage.PERSON_BY_NAME__LAST_NAME:
        setLastName((TextWithSpaces)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case BilangPackage.PERSON_BY_NAME__FIRST_NAME:
        setFirstName(FIRST_NAME_EDEFAULT);
        return;
      case BilangPackage.PERSON_BY_NAME__LAST_NAME:
        setLastName((TextWithSpaces)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case BilangPackage.PERSON_BY_NAME__FIRST_NAME:
        return FIRST_NAME_EDEFAULT == null ? firstName != null : !FIRST_NAME_EDEFAULT.equals(firstName);
      case BilangPackage.PERSON_BY_NAME__LAST_NAME:
        return lastName != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (firstName: ");
    result.append(firstName);
    result.append(')');
    return result.toString();
  }

} //PersonByNameImpl
