/**
 * generated by Xtext 2.44.0
 */
package org.xtext.example.bilang.bilang.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.bilang.bilang.BilangPackage;
import org.xtext.example.bilang.bilang.PersonByEmail;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Person By Email</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.bilang.bilang.impl.PersonByEmailImpl#getEmailaddress <em>Emailaddress</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PersonByEmailImpl extends PersonImpl implements PersonByEmail
{
  /**
   * The default value of the '{@link #getEmailaddress() <em>Emailaddress</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEmailaddress()
   * @generated
   * @ordered
   */
  protected static final String EMAILADDRESS_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getEmailaddress() <em>Emailaddress</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEmailaddress()
   * @generated
   * @ordered
   */
  protected String emailaddress = EMAILADDRESS_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PersonByEmailImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BilangPackage.Literals.PERSON_BY_EMAIL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getEmailaddress()
  {
    return emailaddress;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEmailaddress(String newEmailaddress)
  {
    String oldEmailaddress = emailaddress;
    emailaddress = newEmailaddress;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BilangPackage.PERSON_BY_EMAIL__EMAILADDRESS, oldEmailaddress, emailaddress));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case BilangPackage.PERSON_BY_EMAIL__EMAILADDRESS:
        return getEmailaddress();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case BilangPackage.PERSON_BY_EMAIL__EMAILADDRESS:
        setEmailaddress((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case BilangPackage.PERSON_BY_EMAIL__EMAILADDRESS:
        setEmailaddress(EMAILADDRESS_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case BilangPackage.PERSON_BY_EMAIL__EMAILADDRESS:
        return EMAILADDRESS_EDEFAULT == null ? emailaddress != null : !EMAILADDRESS_EDEFAULT.equals(emailaddress);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (emailaddress: ");
    result.append(emailaddress);
    result.append(')');
    return result.toString();
  }

} //PersonByEmailImpl
