/**
 * generated by Xtext 2.44.0
 */
package org.xtext.example.bilang.bilang.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.bilang.bilang.BilangPackage;
import org.xtext.example.bilang.bilang.RetrievePersons;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Retrieve Persons</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.bilang.bilang.impl.RetrievePersonsImpl#getPersonSearch <em>Person Search</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RetrievePersonsImpl extends RetrieveTaskImpl implements RetrievePersons
{
  /**
   * The default value of the '{@link #getPersonSearch() <em>Person Search</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPersonSearch()
   * @generated
   * @ordered
   */
  protected static final String PERSON_SEARCH_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPersonSearch() <em>Person Search</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPersonSearch()
   * @generated
   * @ordered
   */
  protected String personSearch = PERSON_SEARCH_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RetrievePersonsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BilangPackage.Literals.RETRIEVE_PERSONS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getPersonSearch()
  {
    return personSearch;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPersonSearch(String newPersonSearch)
  {
    String oldPersonSearch = personSearch;
    personSearch = newPersonSearch;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BilangPackage.RETRIEVE_PERSONS__PERSON_SEARCH, oldPersonSearch, personSearch));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case BilangPackage.RETRIEVE_PERSONS__PERSON_SEARCH:
        return getPersonSearch();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case BilangPackage.RETRIEVE_PERSONS__PERSON_SEARCH:
        setPersonSearch((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case BilangPackage.RETRIEVE_PERSONS__PERSON_SEARCH:
        setPersonSearch(PERSON_SEARCH_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case BilangPackage.RETRIEVE_PERSONS__PERSON_SEARCH:
        return PERSON_SEARCH_EDEFAULT == null ? personSearch != null : !PERSON_SEARCH_EDEFAULT.equals(personSearch);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (personSearch: ");
    result.append(personSearch);
    result.append(')');
    return result.toString();
  }

} //RetrievePersonsImpl
