/**
 * generated by Xtext 2.44.0
 */
package org.xtext.example.bilang.bilang.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.bilang.bilang.BilangPackage;
import org.xtext.example.bilang.bilang.Document;
import org.xtext.example.bilang.bilang.RetrieveDocument;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Retrieve Document</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.bilang.bilang.impl.RetrieveDocumentImpl#getDocument <em>Document</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RetrieveDocumentImpl extends RetrieveTaskImpl implements RetrieveDocument
{
  /**
   * The cached value of the '{@link #getDocument() <em>Document</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDocument()
   * @generated
   * @ordered
   */
  protected Document document;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RetrieveDocumentImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BilangPackage.Literals.RETRIEVE_DOCUMENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Document getDocument()
  {
    return document;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDocument(Document newDocument, NotificationChain msgs)
  {
    Document oldDocument = document;
    document = newDocument;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, BilangPackage.RETRIEVE_DOCUMENT__DOCUMENT, oldDocument, newDocument);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDocument(Document newDocument)
  {
    if (newDocument != document)
    {
      NotificationChain msgs = null;
      if (document != null)
        msgs = ((InternalEObject)document).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - BilangPackage.RETRIEVE_DOCUMENT__DOCUMENT, null, msgs);
      if (newDocument != null)
        msgs = ((InternalEObject)newDocument).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - BilangPackage.RETRIEVE_DOCUMENT__DOCUMENT, null, msgs);
      msgs = basicSetDocument(newDocument, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BilangPackage.RETRIEVE_DOCUMENT__DOCUMENT, newDocument, newDocument));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case BilangPackage.RETRIEVE_DOCUMENT__DOCUMENT:
        return basicSetDocument(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case BilangPackage.RETRIEVE_DOCUMENT__DOCUMENT:
        return getDocument();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case BilangPackage.RETRIEVE_DOCUMENT__DOCUMENT:
        setDocument((Document)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case BilangPackage.RETRIEVE_DOCUMENT__DOCUMENT:
        setDocument((Document)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case BilangPackage.RETRIEVE_DOCUMENT__DOCUMENT:
        return document != null;
    }
    return super.eIsSet(featureID);
  }

} //RetrieveDocumentImpl
