/**
 * generated by Xtext 2.44.0
 */
package org.xtext.example.bilang.bilang.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.bilang.bilang.BilangPackage;
import org.xtext.example.bilang.bilang.PersonByAddress;
import org.xtext.example.bilang.bilang.RetrieveFullAddress;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Retrieve Full Address</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.bilang.bilang.impl.RetrieveFullAddressImpl#getPersonAdress <em>Person Adress</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RetrieveFullAddressImpl extends RetrieveTaskImpl implements RetrieveFullAddress
{
  /**
   * The cached value of the '{@link #getPersonAdress() <em>Person Adress</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPersonAdress()
   * @generated
   * @ordered
   */
  protected PersonByAddress personAdress;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RetrieveFullAddressImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BilangPackage.Literals.RETRIEVE_FULL_ADDRESS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PersonByAddress getPersonAdress()
  {
    return personAdress;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetPersonAdress(PersonByAddress newPersonAdress, NotificationChain msgs)
  {
    PersonByAddress oldPersonAdress = personAdress;
    personAdress = newPersonAdress;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, BilangPackage.RETRIEVE_FULL_ADDRESS__PERSON_ADRESS, oldPersonAdress, newPersonAdress);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPersonAdress(PersonByAddress newPersonAdress)
  {
    if (newPersonAdress != personAdress)
    {
      NotificationChain msgs = null;
      if (personAdress != null)
        msgs = ((InternalEObject)personAdress).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - BilangPackage.RETRIEVE_FULL_ADDRESS__PERSON_ADRESS, null, msgs);
      if (newPersonAdress != null)
        msgs = ((InternalEObject)newPersonAdress).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - BilangPackage.RETRIEVE_FULL_ADDRESS__PERSON_ADRESS, null, msgs);
      msgs = basicSetPersonAdress(newPersonAdress, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BilangPackage.RETRIEVE_FULL_ADDRESS__PERSON_ADRESS, newPersonAdress, newPersonAdress));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case BilangPackage.RETRIEVE_FULL_ADDRESS__PERSON_ADRESS:
        return basicSetPersonAdress(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case BilangPackage.RETRIEVE_FULL_ADDRESS__PERSON_ADRESS:
        return getPersonAdress();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case BilangPackage.RETRIEVE_FULL_ADDRESS__PERSON_ADRESS:
        setPersonAdress((PersonByAddress)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case BilangPackage.RETRIEVE_FULL_ADDRESS__PERSON_ADRESS:
        setPersonAdress((PersonByAddress)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case BilangPackage.RETRIEVE_FULL_ADDRESS__PERSON_ADRESS:
        return personAdress != null;
    }
    return super.eIsSet(featureID);
  }

} //RetrieveFullAddressImpl
