/**
 * generated by Xtext 2.44.0
 */
package org.xtext.example.bilang.bilang.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.bilang.bilang.BilangPackage;
import org.xtext.example.bilang.bilang.RetrieveTask;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Retrieve Task</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class RetrieveTaskImpl extends TaskImpl implements RetrieveTask
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RetrieveTaskImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BilangPackage.Literals.RETRIEVE_TASK;
  }

} //RetrieveTaskImpl
