/**
 * generated by Xtext 2.44.0
 */
package org.xtext.example.bilang.bilang.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.bilang.bilang.BilangPackage;
import org.xtext.example.bilang.bilang.SendSnailMail;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Send Snail Mail</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SendSnailMailImpl extends SendTaskImpl implements SendSnailMail
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SendSnailMailImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BilangPackage.Literals.SEND_SNAIL_MAIL;
  }

} //SendSnailMailImpl
