/**
 * generated by Xtext 2.44.0
 */
package org.xtext.example.bilang.bilang.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.bilang.bilang.BilangPackage;
import org.xtext.example.bilang.bilang.SendEmail;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Send Email</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SendEmailImpl extends SendTaskImpl implements SendEmail
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SendEmailImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BilangPackage.Literals.SEND_EMAIL;
  }

} //SendEmailImpl
