/**
 * generated by Xtext 2.44.0
 */
package org.xtext.example.bilang.bilang.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.bilang.bilang.BilangPackage;
import org.xtext.example.bilang.bilang.SendSMS;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Send SMS</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SendSMSImpl extends SendTaskImpl implements SendSMS
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SendSMSImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BilangPackage.Literals.SEND_SMS;
  }

} //SendSMSImpl
