/*
 * generated by Xtext 2.44.0
 */
package org.xtext.example.bilang.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.bilang.BilangRuntimeModule;
import org.xtext.example.bilang.BilangStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class BilangIdeSetup extends BilangStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new BilangRuntimeModule(), new BilangIdeModule()));
	}
	
}
