/*
 * generated by Xtext 2.44.0
 */
package org.xtext.example.bilang.generator

import org.eclipse.emf.ecore.resource.Resource
import org.eclipse.xtext.generator.AbstractGenerator
import org.eclipse.xtext.generator.IFileSystemAccess2
import org.eclipse.xtext.generator.IGeneratorContext
import org.xtext.example.bilang.bilang.Task
import org.xtext.example.bilang.bilang.CompoundProcess
import org.xtext.example.bilang.bilang.AbstractProcess
import org.eclipse.emf.ecore.EObject

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
class BilangGenerator extends AbstractGenerator {

    override void doGenerate(
        Resource resource,
        IFileSystemAccess2 fsa,
        IGeneratorContext context
    ) {
        fsa.generateFile('generated_code.py', toCode(resource))
    }

    def static toCode(Resource resource) {
        '''
        «FOR element : resource.contents»
            «generate(element)»
        «ENDFOR»
        '''
    }

    def static generate(EObject element) {
        switch element {
            Task:
                '''it is a task'''
            CompoundProcess:
                '''it is a compound process'''
            AbstractProcess:
                '''it is an abstract process'''
            default:
                '''not recognized'''
        }
    }
}