/*
 * generated by Xtext 2.44.0
 */
package org.xtext.example.bilang.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.example.bilang.bilang.AbstractProcess;
import org.xtext.example.bilang.bilang.AddPerson;
import org.xtext.example.bilang.bilang.BilangPackage;
import org.xtext.example.bilang.bilang.CallPerson;
import org.xtext.example.bilang.bilang.CompoundProcess;
import org.xtext.example.bilang.bilang.DeletePerson;
import org.xtext.example.bilang.bilang.DocumentPerson;
import org.xtext.example.bilang.bilang.Invoice;
import org.xtext.example.bilang.bilang.Message;
import org.xtext.example.bilang.bilang.ParamValue;
import org.xtext.example.bilang.bilang.PersonByAddress;
import org.xtext.example.bilang.bilang.PersonByAlias;
import org.xtext.example.bilang.bilang.PersonByEmail;
import org.xtext.example.bilang.bilang.PersonByName;
import org.xtext.example.bilang.bilang.PersonByPhone;
import org.xtext.example.bilang.bilang.RetrieveDocument;
import org.xtext.example.bilang.bilang.RetrieveFullAddress;
import org.xtext.example.bilang.bilang.RetrievePersons;
import org.xtext.example.bilang.bilang.SendEmail;
import org.xtext.example.bilang.bilang.SendSMS;
import org.xtext.example.bilang.bilang.SendSnailMail;
import org.xtext.example.bilang.bilang.TextWithSpaces;
import org.xtext.example.bilang.services.BilangGrammarAccess;

@SuppressWarnings("all")
public class BilangSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private BilangGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == BilangPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case BilangPackage.ABSTRACT_PROCESS:
				sequence_AbstractProcess(context, (AbstractProcess) semanticObject); 
				return; 
			case BilangPackage.ADD_PERSON:
				sequence_AddPerson(context, (AddPerson) semanticObject); 
				return; 
			case BilangPackage.CALL_PERSON:
				sequence_CallPerson(context, (CallPerson) semanticObject); 
				return; 
			case BilangPackage.COMPOUND_PROCESS:
				sequence_CompoundProcess(context, (CompoundProcess) semanticObject); 
				return; 
			case BilangPackage.DELETE_PERSON:
				sequence_DeletePerson(context, (DeletePerson) semanticObject); 
				return; 
			case BilangPackage.DOCUMENT_PERSON:
				sequence_DocumentPerson(context, (DocumentPerson) semanticObject); 
				return; 
			case BilangPackage.INVOICE:
				sequence_Invoice(context, (Invoice) semanticObject); 
				return; 
			case BilangPackage.MESSAGE:
				sequence_Message(context, (Message) semanticObject); 
				return; 
			case BilangPackage.PARAM_VALUE:
				sequence_ParamValue(context, (ParamValue) semanticObject); 
				return; 
			case BilangPackage.PERSON_BY_ADDRESS:
				sequence_PersonByAddress(context, (PersonByAddress) semanticObject); 
				return; 
			case BilangPackage.PERSON_BY_ALIAS:
				sequence_PersonByAlias(context, (PersonByAlias) semanticObject); 
				return; 
			case BilangPackage.PERSON_BY_EMAIL:
				sequence_PersonByEmail(context, (PersonByEmail) semanticObject); 
				return; 
			case BilangPackage.PERSON_BY_NAME:
				sequence_PersonByName(context, (PersonByName) semanticObject); 
				return; 
			case BilangPackage.PERSON_BY_PHONE:
				sequence_PersonByPhone(context, (PersonByPhone) semanticObject); 
				return; 
			case BilangPackage.RETRIEVE_DOCUMENT:
				sequence_RetrieveDocument(context, (RetrieveDocument) semanticObject); 
				return; 
			case BilangPackage.RETRIEVE_FULL_ADDRESS:
				sequence_RetrieveFullAddress(context, (RetrieveFullAddress) semanticObject); 
				return; 
			case BilangPackage.RETRIEVE_PERSONS:
				sequence_RetrievePersons(context, (RetrievePersons) semanticObject); 
				return; 
			case BilangPackage.SEND_EMAIL:
				sequence_SendEmail(context, (SendEmail) semanticObject); 
				return; 
			case BilangPackage.SEND_SMS:
				sequence_SendSMS(context, (SendSMS) semanticObject); 
				return; 
			case BilangPackage.SEND_SNAIL_MAIL:
				sequence_SendSnailMail(context, (SendSnailMail) semanticObject); 
				return; 
			case BilangPackage.TEXT_WITH_SPACES:
				sequence_TextWithSpaces(context, (TextWithSpaces) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Model returns AbstractProcess
	 *     AbstractProcess returns AbstractProcess
	 *
	 * Constraint:
	 *     (name=ID paramValues+=ParamValue+)
	 * </pre>
	 */
	protected void sequence_AbstractProcess(ISerializationContext context, AbstractProcess semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Model returns AddPerson
	 *     Task returns AddPerson
	 *     PersonTask returns AddPerson
	 *     AddPerson returns AddPerson
	 *
	 * Constraint:
	 *     (alias=PersonByAlias person+=Person+)
	 * </pre>
	 */
	protected void sequence_AddPerson(ISerializationContext context, AddPerson semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Model returns CallPerson
	 *     Task returns CallPerson
	 *     PersonTask returns CallPerson
	 *     CallPerson returns CallPerson
	 *
	 * Constraint:
	 *     person=Person
	 * </pre>
	 */
	protected void sequence_CallPerson(ISerializationContext context, CallPerson semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BilangPackage.Literals.CALL_PERSON__PERSON) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BilangPackage.Literals.CALL_PERSON__PERSON));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getCallPersonAccess().getPersonPersonParserRuleCall_2_0(), semanticObject.getPerson());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Model returns CompoundProcess
	 *     CompoundProcess returns CompoundProcess
	 *
	 * Constraint:
	 *     task+=Task+
	 * </pre>
	 */
	protected void sequence_CompoundProcess(ISerializationContext context, CompoundProcess semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Model returns DeletePerson
	 *     Task returns DeletePerson
	 *     PersonTask returns DeletePerson
	 *     DeletePerson returns DeletePerson
	 *
	 * Constraint:
	 *     alias=PersonByAlias
	 * </pre>
	 */
	protected void sequence_DeletePerson(ISerializationContext context, DeletePerson semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BilangPackage.Literals.DELETE_PERSON__ALIAS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BilangPackage.Literals.DELETE_PERSON__ALIAS));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getDeletePersonAccess().getAliasPersonByAliasParserRuleCall_1_0(), semanticObject.getAlias());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Content returns DocumentPerson
	 *     Document returns DocumentPerson
	 *     DocumentPerson returns DocumentPerson
	 *
	 * Constraint:
	 *     person=Person
	 * </pre>
	 */
	protected void sequence_DocumentPerson(ISerializationContext context, DocumentPerson semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BilangPackage.Literals.DOCUMENT_PERSON__PERSON) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BilangPackage.Literals.DOCUMENT_PERSON__PERSON));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getDocumentPersonAccess().getPersonPersonParserRuleCall_2_0(), semanticObject.getPerson());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Content returns Invoice
	 *     Document returns Invoice
	 *     Invoice returns Invoice
	 *
	 * Constraint:
	 *     code=INT
	 * </pre>
	 */
	protected void sequence_Invoice(ISerializationContext context, Invoice semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BilangPackage.Literals.INVOICE__CODE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BilangPackage.Literals.INVOICE__CODE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getInvoiceAccess().getCodeINTTerminalRuleCall_3_0(), semanticObject.getCode());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Content returns Message
	 *     Message returns Message
	 *
	 * Constraint:
	 *     message=TextWithSpaces
	 * </pre>
	 */
	protected void sequence_Message(ISerializationContext context, Message semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BilangPackage.Literals.MESSAGE__MESSAGE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BilangPackage.Literals.MESSAGE__MESSAGE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getMessageAccess().getMessageTextWithSpacesParserRuleCall_1_0(), semanticObject.getMessage());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ParamValue returns ParamValue
	 *
	 * Constraint:
	 *     (param=ID value=ID)
	 * </pre>
	 */
	protected void sequence_ParamValue(ISerializationContext context, ParamValue semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BilangPackage.Literals.PARAM_VALUE__PARAM) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BilangPackage.Literals.PARAM_VALUE__PARAM));
			if (transientValues.isValueTransient(semanticObject, BilangPackage.Literals.PARAM_VALUE__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BilangPackage.Literals.PARAM_VALUE__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getParamValueAccess().getParamIDTerminalRuleCall_1_0(), semanticObject.getParam());
		feeder.accept(grammarAccess.getParamValueAccess().getValueIDTerminalRuleCall_3_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Person returns PersonByAddress
	 *     PersonByAddress returns PersonByAddress
	 *
	 * Constraint:
	 *     (zipcode=DUTCH_POSTCODE housenumber=HOUSENUMBER)
	 * </pre>
	 */
	protected void sequence_PersonByAddress(ISerializationContext context, PersonByAddress semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BilangPackage.Literals.PERSON_BY_ADDRESS__ZIPCODE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BilangPackage.Literals.PERSON_BY_ADDRESS__ZIPCODE));
			if (transientValues.isValueTransient(semanticObject, BilangPackage.Literals.PERSON_BY_ADDRESS__HOUSENUMBER) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BilangPackage.Literals.PERSON_BY_ADDRESS__HOUSENUMBER));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getPersonByAddressAccess().getZipcodeDUTCH_POSTCODETerminalRuleCall_4_0(), semanticObject.getZipcode());
		feeder.accept(grammarAccess.getPersonByAddressAccess().getHousenumberHOUSENUMBERTerminalRuleCall_8_0(), semanticObject.getHousenumber());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Person returns PersonByAlias
	 *     PersonByAlias returns PersonByAlias
	 *
	 * Constraint:
	 *     alias=ID
	 * </pre>
	 */
	protected void sequence_PersonByAlias(ISerializationContext context, PersonByAlias semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BilangPackage.Literals.PERSON_BY_ALIAS__ALIAS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BilangPackage.Literals.PERSON_BY_ALIAS__ALIAS));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getPersonByAliasAccess().getAliasIDTerminalRuleCall_3_0(), semanticObject.getAlias());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Person returns PersonByEmail
	 *     PersonByEmail returns PersonByEmail
	 *
	 * Constraint:
	 *     emailaddress=EMAIL_ADDRESS
	 * </pre>
	 */
	protected void sequence_PersonByEmail(ISerializationContext context, PersonByEmail semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BilangPackage.Literals.PERSON_BY_EMAIL__EMAILADDRESS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BilangPackage.Literals.PERSON_BY_EMAIL__EMAILADDRESS));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getPersonByEmailAccess().getEmailaddressEMAIL_ADDRESSTerminalRuleCall_3_0(), semanticObject.getEmailaddress());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Person returns PersonByName
	 *     PersonByName returns PersonByName
	 *
	 * Constraint:
	 *     (firstName=ID lastName=TextWithSpaces)
	 * </pre>
	 */
	protected void sequence_PersonByName(ISerializationContext context, PersonByName semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BilangPackage.Literals.PERSON_BY_NAME__FIRST_NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BilangPackage.Literals.PERSON_BY_NAME__FIRST_NAME));
			if (transientValues.isValueTransient(semanticObject, BilangPackage.Literals.PERSON_BY_NAME__LAST_NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BilangPackage.Literals.PERSON_BY_NAME__LAST_NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getPersonByNameAccess().getFirstNameIDTerminalRuleCall_4_0(), semanticObject.getFirstName());
		feeder.accept(grammarAccess.getPersonByNameAccess().getLastNameTextWithSpacesParserRuleCall_8_0(), semanticObject.getLastName());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Person returns PersonByPhone
	 *     PersonByPhone returns PersonByPhone
	 *
	 * Constraint:
	 *     phone=PHONE_NUMBER
	 * </pre>
	 */
	protected void sequence_PersonByPhone(ISerializationContext context, PersonByPhone semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BilangPackage.Literals.PERSON_BY_PHONE__PHONE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BilangPackage.Literals.PERSON_BY_PHONE__PHONE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getPersonByPhoneAccess().getPhonePHONE_NUMBERTerminalRuleCall_4_0(), semanticObject.getPhone());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Model returns RetrieveDocument
	 *     Task returns RetrieveDocument
	 *     RetrieveTask returns RetrieveDocument
	 *     RetrieveDocument returns RetrieveDocument
	 *
	 * Constraint:
	 *     document=Document
	 * </pre>
	 */
	protected void sequence_RetrieveDocument(ISerializationContext context, RetrieveDocument semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BilangPackage.Literals.RETRIEVE_DOCUMENT__DOCUMENT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BilangPackage.Literals.RETRIEVE_DOCUMENT__DOCUMENT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getRetrieveDocumentAccess().getDocumentDocumentParserRuleCall_2_0(), semanticObject.getDocument());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Model returns RetrieveFullAddress
	 *     Task returns RetrieveFullAddress
	 *     RetrieveTask returns RetrieveFullAddress
	 *     RetrieveFullAddress returns RetrieveFullAddress
	 *
	 * Constraint:
	 *     personAdress=PersonByAddress
	 * </pre>
	 */
	protected void sequence_RetrieveFullAddress(ISerializationContext context, RetrieveFullAddress semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BilangPackage.Literals.RETRIEVE_FULL_ADDRESS__PERSON_ADRESS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BilangPackage.Literals.RETRIEVE_FULL_ADDRESS__PERSON_ADRESS));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getRetrieveFullAddressAccess().getPersonAdressPersonByAddressParserRuleCall_4_0(), semanticObject.getPersonAdress());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Model returns RetrievePersons
	 *     Task returns RetrievePersons
	 *     RetrieveTask returns RetrievePersons
	 *     RetrievePersons returns RetrievePersons
	 *
	 * Constraint:
	 *     personSearch=ID
	 * </pre>
	 */
	protected void sequence_RetrievePersons(ISerializationContext context, RetrievePersons semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BilangPackage.Literals.RETRIEVE_PERSONS__PERSON_SEARCH) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BilangPackage.Literals.RETRIEVE_PERSONS__PERSON_SEARCH));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getRetrievePersonsAccess().getPersonSearchIDTerminalRuleCall_4_0(), semanticObject.getPersonSearch());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Model returns SendEmail
	 *     Task returns SendEmail
	 *     SendTask returns SendEmail
	 *     SendEmail returns SendEmail
	 *
	 * Constraint:
	 *     (person+=Person+ content=Content)
	 * </pre>
	 */
	protected void sequence_SendEmail(ISerializationContext context, SendEmail semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Model returns SendSMS
	 *     Task returns SendSMS
	 *     SendTask returns SendSMS
	 *     SendSMS returns SendSMS
	 *
	 * Constraint:
	 *     (person+=Person+ content=Content)
	 * </pre>
	 */
	protected void sequence_SendSMS(ISerializationContext context, SendSMS semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Model returns SendSnailMail
	 *     Task returns SendSnailMail
	 *     SendTask returns SendSnailMail
	 *     SendSnailMail returns SendSnailMail
	 *
	 * Constraint:
	 *     (person+=Person+ content=Content)
	 * </pre>
	 */
	protected void sequence_SendSnailMail(ISerializationContext context, SendSnailMail semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TextWithSpaces returns TextWithSpaces
	 *
	 * Constraint:
	 *     (parts+=ID parts+=ID+)
	 * </pre>
	 */
	protected void sequence_TextWithSpaces(ISerializationContext context, TextWithSpaces semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
