/*
 * generated by Xtext 2.44.0
 */
package org.xtext.example.bilang.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.bilang.ui.internal.BilangActivator;

public class BilangUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return BilangActivator.getInstance().getInjector("org.xtext.example.bilang.Bilang");
	}

}
