/*
 * generated by Xtext 2.44.0
 */
package org.xtext.example.bilang.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.bilang.ui.internal.BilangActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class BilangExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(BilangActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		BilangActivator activator = BilangActivator.getInstance();
		return activator != null ? activator.getInjector(BilangActivator.ORG_XTEXT_EXAMPLE_BILANG_BILANG) : null;
	}

}
