/*
 * generated by Xtext 2.44.0
 */
package org.xtext.example.bilang.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.bilang.parser.antlr.internal.InternalBilangParser;
import org.xtext.example.bilang.services.BilangGrammarAccess;

public class BilangParser extends AbstractAntlrParser {

	@Inject
	private BilangGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalBilangParser createParser(XtextTokenStream stream) {
		return new InternalBilangParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public BilangGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(BilangGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
