/**
 * generated by Xtext 2.44.0
 */
package org.xtext.example.bilang.generator;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.xtext.example.bilang.bilang.AbstractProcess;
import org.xtext.example.bilang.bilang.CompoundProcess;
import org.xtext.example.bilang.bilang.Task;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class BilangGenerator extends AbstractGenerator {
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    fsa.generateFile("generated_code.py", BilangGenerator.toCode(resource));
  }

  public static CharSequence toCode(final Resource resource) {
    StringConcatenation _builder = new StringConcatenation();
    {
      EList<EObject> _contents = resource.getContents();
      for(final EObject element : _contents) {
        CharSequence _generate = BilangGenerator.generate(element);
        _builder.append(_generate);
        _builder.newLineIfNotEmpty();
      }
    }
    return _builder;
  }

  public static CharSequence generate(final EObject element) {
    CharSequence _switchResult = null;
    boolean _matched = false;
    if (element instanceof Task) {
      _matched=true;
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("it is a task");
      _switchResult = _builder;
    }
    if (!_matched) {
      if (element instanceof CompoundProcess) {
        _matched=true;
        StringConcatenation _builder = new StringConcatenation();
        _builder.append("it is a compound process");
        _switchResult = _builder;
      }
    }
    if (!_matched) {
      if (element instanceof AbstractProcess) {
        _matched=true;
        StringConcatenation _builder = new StringConcatenation();
        _builder.append("it is an abstract process");
        _switchResult = _builder;
      }
    }
    if (!_matched) {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("not recognized");
      _switchResult = _builder;
    }
    return _switchResult;
  }
}
