/**
 * generated by Xtext 2.44.0
 */
package org.xtext.example.bilang.bilang.util;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.util.Switch;

import org.xtext.example.bilang.bilang.*;

/**
 * <!-- begin-user-doc -->
 * The <b>Switch</b> for the model's inheritance hierarchy.
 * It supports the call {@link #doSwitch(EObject) doSwitch(object)}
 * to invoke the <code>caseXXX</code> method for each class of the model,
 * starting with the actual class of the object
 * and proceeding up the inheritance hierarchy
 * until a non-null result is returned,
 * which is the result of the switch.
 * <!-- end-user-doc -->
 * @see org.xtext.example.bilang.bilang.BilangPackage
 * @generated
 */
public class BilangSwitch<T> extends Switch<T>
{
  /**
   * The cached model package
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static BilangPackage modelPackage;

  /**
   * Creates an instance of the switch.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BilangSwitch()
  {
    if (modelPackage == null)
    {
      modelPackage = BilangPackage.eINSTANCE;
    }
  }

  /**
   * Checks whether this is a switch for the given package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param ePackage the package in question.
   * @return whether this is a switch for the given package.
   * @generated
   */
  @Override
  protected boolean isSwitchFor(EPackage ePackage)
  {
    return ePackage == modelPackage;
  }

  /**
   * Calls <code>caseXXX</code> for each class of the model until one returns a non null result; it yields that result.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the first non-null result returned by a <code>caseXXX</code> call.
   * @generated
   */
  @Override
  protected T doSwitch(int classifierID, EObject theEObject)
  {
    switch (classifierID)
    {
      case BilangPackage.MODEL:
      {
        Model model = (Model)theEObject;
        T result = caseModel(model);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case BilangPackage.TASK:
      {
        Task task = (Task)theEObject;
        T result = caseTask(task);
        if (result == null) result = caseModel(task);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case BilangPackage.COMPOUND_PROCESS:
      {
        CompoundProcess compoundProcess = (CompoundProcess)theEObject;
        T result = caseCompoundProcess(compoundProcess);
        if (result == null) result = caseModel(compoundProcess);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case BilangPackage.ABSTRACT_PROCESS:
      {
        AbstractProcess abstractProcess = (AbstractProcess)theEObject;
        T result = caseAbstractProcess(abstractProcess);
        if (result == null) result = caseModel(abstractProcess);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case BilangPackage.PARAM_VALUE:
      {
        ParamValue paramValue = (ParamValue)theEObject;
        T result = caseParamValue(paramValue);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case BilangPackage.RETRIEVE_TASK:
      {
        RetrieveTask retrieveTask = (RetrieveTask)theEObject;
        T result = caseRetrieveTask(retrieveTask);
        if (result == null) result = caseTask(retrieveTask);
        if (result == null) result = caseModel(retrieveTask);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case BilangPackage.SEND_TASK:
      {
        SendTask sendTask = (SendTask)theEObject;
        T result = caseSendTask(sendTask);
        if (result == null) result = caseTask(sendTask);
        if (result == null) result = caseModel(sendTask);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case BilangPackage.PERSON_TASK:
      {
        PersonTask personTask = (PersonTask)theEObject;
        T result = casePersonTask(personTask);
        if (result == null) result = caseTask(personTask);
        if (result == null) result = caseModel(personTask);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case BilangPackage.SEND_EMAIL:
      {
        SendEmail sendEmail = (SendEmail)theEObject;
        T result = caseSendEmail(sendEmail);
        if (result == null) result = caseSendTask(sendEmail);
        if (result == null) result = caseTask(sendEmail);
        if (result == null) result = caseModel(sendEmail);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case BilangPackage.SEND_SMS:
      {
        SendSMS sendSMS = (SendSMS)theEObject;
        T result = caseSendSMS(sendSMS);
        if (result == null) result = caseSendTask(sendSMS);
        if (result == null) result = caseTask(sendSMS);
        if (result == null) result = caseModel(sendSMS);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case BilangPackage.SEND_SNAIL_MAIL:
      {
        SendSnailMail sendSnailMail = (SendSnailMail)theEObject;
        T result = caseSendSnailMail(sendSnailMail);
        if (result == null) result = caseSendTask(sendSnailMail);
        if (result == null) result = caseTask(sendSnailMail);
        if (result == null) result = caseModel(sendSnailMail);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case BilangPackage.RETRIEVE_DOCUMENT:
      {
        RetrieveDocument retrieveDocument = (RetrieveDocument)theEObject;
        T result = caseRetrieveDocument(retrieveDocument);
        if (result == null) result = caseRetrieveTask(retrieveDocument);
        if (result == null) result = caseTask(retrieveDocument);
        if (result == null) result = caseModel(retrieveDocument);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case BilangPackage.RETRIEVE_FULL_ADDRESS:
      {
        RetrieveFullAddress retrieveFullAddress = (RetrieveFullAddress)theEObject;
        T result = caseRetrieveFullAddress(retrieveFullAddress);
        if (result == null) result = caseRetrieveTask(retrieveFullAddress);
        if (result == null) result = caseTask(retrieveFullAddress);
        if (result == null) result = caseModel(retrieveFullAddress);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case BilangPackage.RETRIEVE_PERSONS:
      {
        RetrievePersons retrievePersons = (RetrievePersons)theEObject;
        T result = caseRetrievePersons(retrievePersons);
        if (result == null) result = caseRetrieveTask(retrievePersons);
        if (result == null) result = caseTask(retrievePersons);
        if (result == null) result = caseModel(retrievePersons);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case BilangPackage.CALL_PERSON:
      {
        CallPerson callPerson = (CallPerson)theEObject;
        T result = caseCallPerson(callPerson);
        if (result == null) result = casePersonTask(callPerson);
        if (result == null) result = caseTask(callPerson);
        if (result == null) result = caseModel(callPerson);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case BilangPackage.ADD_PERSON:
      {
        AddPerson addPerson = (AddPerson)theEObject;
        T result = caseAddPerson(addPerson);
        if (result == null) result = casePersonTask(addPerson);
        if (result == null) result = caseTask(addPerson);
        if (result == null) result = caseModel(addPerson);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case BilangPackage.DELETE_PERSON:
      {
        DeletePerson deletePerson = (DeletePerson)theEObject;
        T result = caseDeletePerson(deletePerson);
        if (result == null) result = casePersonTask(deletePerson);
        if (result == null) result = caseTask(deletePerson);
        if (result == null) result = caseModel(deletePerson);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case BilangPackage.PERSON:
      {
        Person person = (Person)theEObject;
        T result = casePerson(person);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case BilangPackage.PERSON_BY_EMAIL:
      {
        PersonByEmail personByEmail = (PersonByEmail)theEObject;
        T result = casePersonByEmail(personByEmail);
        if (result == null) result = casePerson(personByEmail);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case BilangPackage.PERSON_BY_ALIAS:
      {
        PersonByAlias personByAlias = (PersonByAlias)theEObject;
        T result = casePersonByAlias(personByAlias);
        if (result == null) result = casePerson(personByAlias);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case BilangPackage.PERSON_BY_NAME:
      {
        PersonByName personByName = (PersonByName)theEObject;
        T result = casePersonByName(personByName);
        if (result == null) result = casePerson(personByName);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case BilangPackage.PERSON_BY_PHONE:
      {
        PersonByPhone personByPhone = (PersonByPhone)theEObject;
        T result = casePersonByPhone(personByPhone);
        if (result == null) result = casePerson(personByPhone);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case BilangPackage.PERSON_BY_ADDRESS:
      {
        PersonByAddress personByAddress = (PersonByAddress)theEObject;
        T result = casePersonByAddress(personByAddress);
        if (result == null) result = casePerson(personByAddress);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case BilangPackage.CONTENT:
      {
        Content content = (Content)theEObject;
        T result = caseContent(content);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case BilangPackage.MESSAGE:
      {
        Message message = (Message)theEObject;
        T result = caseMessage(message);
        if (result == null) result = caseContent(message);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case BilangPackage.DOCUMENT:
      {
        Document document = (Document)theEObject;
        T result = caseDocument(document);
        if (result == null) result = caseContent(document);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case BilangPackage.INVOICE:
      {
        Invoice invoice = (Invoice)theEObject;
        T result = caseInvoice(invoice);
        if (result == null) result = caseDocument(invoice);
        if (result == null) result = caseContent(invoice);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case BilangPackage.DOCUMENT_PERSON:
      {
        DocumentPerson documentPerson = (DocumentPerson)theEObject;
        T result = caseDocumentPerson(documentPerson);
        if (result == null) result = caseDocument(documentPerson);
        if (result == null) result = caseContent(documentPerson);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case BilangPackage.TEXT_WITH_SPACES:
      {
        TextWithSpaces textWithSpaces = (TextWithSpaces)theEObject;
        T result = caseTextWithSpaces(textWithSpaces);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      default: return defaultCase(theEObject);
    }
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Model</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseModel(Model object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Task</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Task</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseTask(Task object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Compound Process</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Compound Process</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseCompoundProcess(CompoundProcess object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Abstract Process</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Abstract Process</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseAbstractProcess(AbstractProcess object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Param Value</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Param Value</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseParamValue(ParamValue object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Retrieve Task</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Retrieve Task</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseRetrieveTask(RetrieveTask object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Send Task</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Send Task</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSendTask(SendTask object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Person Task</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Person Task</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casePersonTask(PersonTask object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Send Email</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Send Email</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSendEmail(SendEmail object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Send SMS</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Send SMS</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSendSMS(SendSMS object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Send Snail Mail</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Send Snail Mail</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSendSnailMail(SendSnailMail object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Retrieve Document</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Retrieve Document</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseRetrieveDocument(RetrieveDocument object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Retrieve Full Address</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Retrieve Full Address</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseRetrieveFullAddress(RetrieveFullAddress object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Retrieve Persons</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Retrieve Persons</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseRetrievePersons(RetrievePersons object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Call Person</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Call Person</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseCallPerson(CallPerson object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Add Person</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Add Person</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseAddPerson(AddPerson object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Delete Person</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Delete Person</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseDeletePerson(DeletePerson object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Person</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Person</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casePerson(Person object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Person By Email</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Person By Email</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casePersonByEmail(PersonByEmail object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Person By Alias</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Person By Alias</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casePersonByAlias(PersonByAlias object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Person By Name</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Person By Name</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casePersonByName(PersonByName object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Person By Phone</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Person By Phone</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casePersonByPhone(PersonByPhone object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Person By Address</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Person By Address</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casePersonByAddress(PersonByAddress object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Content</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Content</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseContent(Content object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Message</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Message</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseMessage(Message object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Document</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Document</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseDocument(Document object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Invoice</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Invoice</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseInvoice(Invoice object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Document Person</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Document Person</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseDocumentPerson(DocumentPerson object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Text With Spaces</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Text With Spaces</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseTextWithSpaces(TextWithSpaces object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EObject</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch, but this is the last case anyway.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EObject</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject)
   * @generated
   */
  @Override
  public T defaultCase(EObject object)
  {
    return null;
  }

} //BilangSwitch
