/*
 * generated by Xtext 2.44.0
 */
package org.xtext.example.bilang;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class BilangStandaloneSetup extends BilangStandaloneSetupGenerated {

	public static void doSetup() {
		new BilangStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
