/*
 * generated by Xtext 2.44.0
 */
package org.xtext.example.bilang.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractBilangScopeProvider extends DelegatingScopeProvider {
}
