/**
 * generated by Xtext 2.44.0
 */
package org.xtext.example.bilang.bilang;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Abstract Process</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.bilang.bilang.AbstractProcess#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.bilang.bilang.AbstractProcess#getParamValues <em>Param Values</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.bilang.bilang.BilangPackage#getAbstractProcess()
 * @model
 * @generated
 */
public interface AbstractProcess extends Model
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.bilang.bilang.BilangPackage#getAbstractProcess_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.bilang.bilang.AbstractProcess#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Param Values</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.bilang.bilang.ParamValue}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Param Values</em>' containment reference list.
   * @see org.xtext.example.bilang.bilang.BilangPackage#getAbstractProcess_ParamValues()
   * @model containment="true"
   * @generated
   */
  EList<ParamValue> getParamValues();

} // AbstractProcess
