/**
 * generated by Xtext 2.44.0
 */
package org.xtext.example.bilang.bilang;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Add Person</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.bilang.bilang.AddPerson#getAlias <em>Alias</em>}</li>
 *   <li>{@link org.xtext.example.bilang.bilang.AddPerson#getPerson <em>Person</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.bilang.bilang.BilangPackage#getAddPerson()
 * @model
 * @generated
 */
public interface AddPerson extends PersonTask
{
  /**
   * Returns the value of the '<em><b>Alias</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Alias</em>' containment reference.
   * @see #setAlias(PersonByAlias)
   * @see org.xtext.example.bilang.bilang.BilangPackage#getAddPerson_Alias()
   * @model containment="true"
   * @generated
   */
  PersonByAlias getAlias();

  /**
   * Sets the value of the '{@link org.xtext.example.bilang.bilang.AddPerson#getAlias <em>Alias</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Alias</em>' containment reference.
   * @see #getAlias()
   * @generated
   */
  void setAlias(PersonByAlias value);

  /**
   * Returns the value of the '<em><b>Person</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.bilang.bilang.Person}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Person</em>' containment reference list.
   * @see org.xtext.example.bilang.bilang.BilangPackage#getAddPerson_Person()
   * @model containment="true"
   * @generated
   */
  EList<Person> getPerson();

} // AddPerson
