/**
 * generated by Xtext 2.44.0
 */
package org.xtext.example.bilang.bilang;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.example.bilang.bilang.BilangPackage
 * @generated
 */
public interface BilangFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  BilangFactory eINSTANCE = org.xtext.example.bilang.bilang.impl.BilangFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Task</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Task</em>'.
   * @generated
   */
  Task createTask();

  /**
   * Returns a new object of class '<em>Compound Process</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Compound Process</em>'.
   * @generated
   */
  CompoundProcess createCompoundProcess();

  /**
   * Returns a new object of class '<em>Abstract Process</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Abstract Process</em>'.
   * @generated
   */
  AbstractProcess createAbstractProcess();

  /**
   * Returns a new object of class '<em>Param Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Param Value</em>'.
   * @generated
   */
  ParamValue createParamValue();

  /**
   * Returns a new object of class '<em>Retrieve Task</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Retrieve Task</em>'.
   * @generated
   */
  RetrieveTask createRetrieveTask();

  /**
   * Returns a new object of class '<em>Send Task</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Send Task</em>'.
   * @generated
   */
  SendTask createSendTask();

  /**
   * Returns a new object of class '<em>Person Task</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Person Task</em>'.
   * @generated
   */
  PersonTask createPersonTask();

  /**
   * Returns a new object of class '<em>Send Email</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Send Email</em>'.
   * @generated
   */
  SendEmail createSendEmail();

  /**
   * Returns a new object of class '<em>Send SMS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Send SMS</em>'.
   * @generated
   */
  SendSMS createSendSMS();

  /**
   * Returns a new object of class '<em>Send Snail Mail</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Send Snail Mail</em>'.
   * @generated
   */
  SendSnailMail createSendSnailMail();

  /**
   * Returns a new object of class '<em>Retrieve Document</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Retrieve Document</em>'.
   * @generated
   */
  RetrieveDocument createRetrieveDocument();

  /**
   * Returns a new object of class '<em>Retrieve Full Address</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Retrieve Full Address</em>'.
   * @generated
   */
  RetrieveFullAddress createRetrieveFullAddress();

  /**
   * Returns a new object of class '<em>Retrieve Persons</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Retrieve Persons</em>'.
   * @generated
   */
  RetrievePersons createRetrievePersons();

  /**
   * Returns a new object of class '<em>Call Person</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Call Person</em>'.
   * @generated
   */
  CallPerson createCallPerson();

  /**
   * Returns a new object of class '<em>Add Person</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Add Person</em>'.
   * @generated
   */
  AddPerson createAddPerson();

  /**
   * Returns a new object of class '<em>Delete Person</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Delete Person</em>'.
   * @generated
   */
  DeletePerson createDeletePerson();

  /**
   * Returns a new object of class '<em>Person</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Person</em>'.
   * @generated
   */
  Person createPerson();

  /**
   * Returns a new object of class '<em>Person By Email</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Person By Email</em>'.
   * @generated
   */
  PersonByEmail createPersonByEmail();

  /**
   * Returns a new object of class '<em>Person By Alias</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Person By Alias</em>'.
   * @generated
   */
  PersonByAlias createPersonByAlias();

  /**
   * Returns a new object of class '<em>Person By Name</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Person By Name</em>'.
   * @generated
   */
  PersonByName createPersonByName();

  /**
   * Returns a new object of class '<em>Person By Phone</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Person By Phone</em>'.
   * @generated
   */
  PersonByPhone createPersonByPhone();

  /**
   * Returns a new object of class '<em>Person By Address</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Person By Address</em>'.
   * @generated
   */
  PersonByAddress createPersonByAddress();

  /**
   * Returns a new object of class '<em>Content</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Content</em>'.
   * @generated
   */
  Content createContent();

  /**
   * Returns a new object of class '<em>Message</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Message</em>'.
   * @generated
   */
  Message createMessage();

  /**
   * Returns a new object of class '<em>Document</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Document</em>'.
   * @generated
   */
  Document createDocument();

  /**
   * Returns a new object of class '<em>Invoice</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Invoice</em>'.
   * @generated
   */
  Invoice createInvoice();

  /**
   * Returns a new object of class '<em>Document Person</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Document Person</em>'.
   * @generated
   */
  DocumentPerson createDocumentPerson();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  BilangPackage getBilangPackage();

} //BilangFactory
