/**
 * generated by Xtext 2.44.0
 */
package org.xtext.example.bilang.bilang;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.bilang.bilang.BilangFactory
 * @model kind="package"
 * @generated
 */
public interface BilangPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "bilang";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/bilang/Bilang";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "bilang";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  BilangPackage eINSTANCE = org.xtext.example.bilang.bilang.impl.BilangPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.bilang.bilang.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.bilang.bilang.impl.ModelImpl
   * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.bilang.bilang.impl.TaskImpl <em>Task</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.bilang.bilang.impl.TaskImpl
   * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getTask()
   * @generated
   */
  int TASK = 1;

  /**
   * The feature id for the '<em><b>Kind</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__KIND = MODEL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Task</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_FEATURE_COUNT = MODEL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.bilang.bilang.impl.CompoundProcessImpl <em>Compound Process</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.bilang.bilang.impl.CompoundProcessImpl
   * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getCompoundProcess()
   * @generated
   */
  int COMPOUND_PROCESS = 2;

  /**
   * The feature id for the '<em><b>Task</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPOUND_PROCESS__TASK = MODEL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Compound Process</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPOUND_PROCESS_FEATURE_COUNT = MODEL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.bilang.bilang.impl.AbstractProcessImpl <em>Abstract Process</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.bilang.bilang.impl.AbstractProcessImpl
   * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getAbstractProcess()
   * @generated
   */
  int ABSTRACT_PROCESS = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_PROCESS__NAME = MODEL_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Param Values</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_PROCESS__PARAM_VALUES = MODEL_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Abstract Process</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_PROCESS_FEATURE_COUNT = MODEL_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.bilang.bilang.impl.ParamValueImpl <em>Param Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.bilang.bilang.impl.ParamValueImpl
   * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getParamValue()
   * @generated
   */
  int PARAM_VALUE = 4;

  /**
   * The feature id for the '<em><b>Param</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM_VALUE__PARAM = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM_VALUE__VALUE = 1;

  /**
   * The number of structural features of the '<em>Param Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM_VALUE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.bilang.bilang.impl.RetrieveTaskImpl <em>Retrieve Task</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.bilang.bilang.impl.RetrieveTaskImpl
   * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getRetrieveTask()
   * @generated
   */
  int RETRIEVE_TASK = 5;

  /**
   * The number of structural features of the '<em>Retrieve Task</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RETRIEVE_TASK_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.bilang.bilang.impl.SendTaskImpl <em>Send Task</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.bilang.bilang.impl.SendTaskImpl
   * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getSendTask()
   * @generated
   */
  int SEND_TASK = 6;

  /**
   * The feature id for the '<em><b>Person</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEND_TASK__PERSON = 0;

  /**
   * The feature id for the '<em><b>Content</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEND_TASK__CONTENT = 1;

  /**
   * The number of structural features of the '<em>Send Task</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEND_TASK_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.bilang.bilang.impl.PersonTaskImpl <em>Person Task</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.bilang.bilang.impl.PersonTaskImpl
   * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getPersonTask()
   * @generated
   */
  int PERSON_TASK = 7;

  /**
   * The number of structural features of the '<em>Person Task</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON_TASK_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.bilang.bilang.impl.SendEmailImpl <em>Send Email</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.bilang.bilang.impl.SendEmailImpl
   * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getSendEmail()
   * @generated
   */
  int SEND_EMAIL = 8;

  /**
   * The feature id for the '<em><b>Person</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEND_EMAIL__PERSON = SEND_TASK__PERSON;

  /**
   * The feature id for the '<em><b>Content</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEND_EMAIL__CONTENT = SEND_TASK__CONTENT;

  /**
   * The number of structural features of the '<em>Send Email</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEND_EMAIL_FEATURE_COUNT = SEND_TASK_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.bilang.bilang.impl.SendSMSImpl <em>Send SMS</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.bilang.bilang.impl.SendSMSImpl
   * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getSendSMS()
   * @generated
   */
  int SEND_SMS = 9;

  /**
   * The feature id for the '<em><b>Person</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEND_SMS__PERSON = SEND_TASK__PERSON;

  /**
   * The feature id for the '<em><b>Content</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEND_SMS__CONTENT = SEND_TASK__CONTENT;

  /**
   * The number of structural features of the '<em>Send SMS</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEND_SMS_FEATURE_COUNT = SEND_TASK_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.bilang.bilang.impl.SendSnailMailImpl <em>Send Snail Mail</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.bilang.bilang.impl.SendSnailMailImpl
   * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getSendSnailMail()
   * @generated
   */
  int SEND_SNAIL_MAIL = 10;

  /**
   * The feature id for the '<em><b>Person</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEND_SNAIL_MAIL__PERSON = SEND_TASK__PERSON;

  /**
   * The feature id for the '<em><b>Content</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEND_SNAIL_MAIL__CONTENT = SEND_TASK__CONTENT;

  /**
   * The number of structural features of the '<em>Send Snail Mail</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEND_SNAIL_MAIL_FEATURE_COUNT = SEND_TASK_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.bilang.bilang.impl.RetrieveDocumentImpl <em>Retrieve Document</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.bilang.bilang.impl.RetrieveDocumentImpl
   * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getRetrieveDocument()
   * @generated
   */
  int RETRIEVE_DOCUMENT = 11;

  /**
   * The feature id for the '<em><b>Document</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RETRIEVE_DOCUMENT__DOCUMENT = RETRIEVE_TASK_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Retrieve Document</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RETRIEVE_DOCUMENT_FEATURE_COUNT = RETRIEVE_TASK_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.bilang.bilang.impl.RetrieveFullAddressImpl <em>Retrieve Full Address</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.bilang.bilang.impl.RetrieveFullAddressImpl
   * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getRetrieveFullAddress()
   * @generated
   */
  int RETRIEVE_FULL_ADDRESS = 12;

  /**
   * The feature id for the '<em><b>Person Adress</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RETRIEVE_FULL_ADDRESS__PERSON_ADRESS = RETRIEVE_TASK_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Retrieve Full Address</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RETRIEVE_FULL_ADDRESS_FEATURE_COUNT = RETRIEVE_TASK_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.bilang.bilang.impl.RetrievePersonsImpl <em>Retrieve Persons</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.bilang.bilang.impl.RetrievePersonsImpl
   * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getRetrievePersons()
   * @generated
   */
  int RETRIEVE_PERSONS = 13;

  /**
   * The feature id for the '<em><b>Person Search</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RETRIEVE_PERSONS__PERSON_SEARCH = RETRIEVE_TASK_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Retrieve Persons</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RETRIEVE_PERSONS_FEATURE_COUNT = RETRIEVE_TASK_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.bilang.bilang.impl.CallPersonImpl <em>Call Person</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.bilang.bilang.impl.CallPersonImpl
   * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getCallPerson()
   * @generated
   */
  int CALL_PERSON = 14;

  /**
   * The feature id for the '<em><b>Person</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALL_PERSON__PERSON = PERSON_TASK_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Call Person</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALL_PERSON_FEATURE_COUNT = PERSON_TASK_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.bilang.bilang.impl.AddPersonImpl <em>Add Person</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.bilang.bilang.impl.AddPersonImpl
   * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getAddPerson()
   * @generated
   */
  int ADD_PERSON = 15;

  /**
   * The feature id for the '<em><b>Alias</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_PERSON__ALIAS = PERSON_TASK_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Person</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_PERSON__PERSON = PERSON_TASK_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Add Person</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_PERSON_FEATURE_COUNT = PERSON_TASK_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.bilang.bilang.impl.DeletePersonImpl <em>Delete Person</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.bilang.bilang.impl.DeletePersonImpl
   * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getDeletePerson()
   * @generated
   */
  int DELETE_PERSON = 16;

  /**
   * The feature id for the '<em><b>Alias</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DELETE_PERSON__ALIAS = PERSON_TASK_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Delete Person</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DELETE_PERSON_FEATURE_COUNT = PERSON_TASK_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.bilang.bilang.impl.PersonImpl <em>Person</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.bilang.bilang.impl.PersonImpl
   * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getPerson()
   * @generated
   */
  int PERSON = 17;

  /**
   * The number of structural features of the '<em>Person</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.bilang.bilang.impl.PersonByEmailImpl <em>Person By Email</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.bilang.bilang.impl.PersonByEmailImpl
   * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getPersonByEmail()
   * @generated
   */
  int PERSON_BY_EMAIL = 18;

  /**
   * The feature id for the '<em><b>Emailaddress</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON_BY_EMAIL__EMAILADDRESS = PERSON_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Person By Email</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON_BY_EMAIL_FEATURE_COUNT = PERSON_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.bilang.bilang.impl.PersonByAliasImpl <em>Person By Alias</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.bilang.bilang.impl.PersonByAliasImpl
   * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getPersonByAlias()
   * @generated
   */
  int PERSON_BY_ALIAS = 19;

  /**
   * The feature id for the '<em><b>Alias</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON_BY_ALIAS__ALIAS = PERSON_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Person By Alias</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON_BY_ALIAS_FEATURE_COUNT = PERSON_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.bilang.bilang.impl.PersonByNameImpl <em>Person By Name</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.bilang.bilang.impl.PersonByNameImpl
   * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getPersonByName()
   * @generated
   */
  int PERSON_BY_NAME = 20;

  /**
   * The feature id for the '<em><b>First Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON_BY_NAME__FIRST_NAME = PERSON_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Last Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON_BY_NAME__LAST_NAME = PERSON_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Person By Name</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON_BY_NAME_FEATURE_COUNT = PERSON_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.bilang.bilang.impl.PersonByPhoneImpl <em>Person By Phone</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.bilang.bilang.impl.PersonByPhoneImpl
   * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getPersonByPhone()
   * @generated
   */
  int PERSON_BY_PHONE = 21;

  /**
   * The feature id for the '<em><b>Phone</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON_BY_PHONE__PHONE = PERSON_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Person By Phone</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON_BY_PHONE_FEATURE_COUNT = PERSON_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.bilang.bilang.impl.PersonByAddressImpl <em>Person By Address</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.bilang.bilang.impl.PersonByAddressImpl
   * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getPersonByAddress()
   * @generated
   */
  int PERSON_BY_ADDRESS = 22;

  /**
   * The feature id for the '<em><b>Zipcode</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON_BY_ADDRESS__ZIPCODE = PERSON_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Housenumber</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON_BY_ADDRESS__HOUSENUMBER = PERSON_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Person By Address</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSON_BY_ADDRESS_FEATURE_COUNT = PERSON_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.bilang.bilang.impl.ContentImpl <em>Content</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.bilang.bilang.impl.ContentImpl
   * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getContent()
   * @generated
   */
  int CONTENT = 23;

  /**
   * The number of structural features of the '<em>Content</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.bilang.bilang.impl.MessageImpl <em>Message</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.bilang.bilang.impl.MessageImpl
   * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getMessage()
   * @generated
   */
  int MESSAGE = 24;

  /**
   * The feature id for the '<em><b>Message</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE__MESSAGE = CONTENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Message</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_FEATURE_COUNT = CONTENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.bilang.bilang.impl.DocumentImpl <em>Document</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.bilang.bilang.impl.DocumentImpl
   * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getDocument()
   * @generated
   */
  int DOCUMENT = 25;

  /**
   * The number of structural features of the '<em>Document</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOCUMENT_FEATURE_COUNT = CONTENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.bilang.bilang.impl.InvoiceImpl <em>Invoice</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.bilang.bilang.impl.InvoiceImpl
   * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getInvoice()
   * @generated
   */
  int INVOICE = 26;

  /**
   * The feature id for the '<em><b>Code</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INVOICE__CODE = DOCUMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Invoice</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INVOICE_FEATURE_COUNT = DOCUMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.bilang.bilang.impl.DocumentPersonImpl <em>Document Person</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.bilang.bilang.impl.DocumentPersonImpl
   * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getDocumentPerson()
   * @generated
   */
  int DOCUMENT_PERSON = 27;

  /**
   * The feature id for the '<em><b>Person</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOCUMENT_PERSON__PERSON = DOCUMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Document Person</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOCUMENT_PERSON_FEATURE_COUNT = DOCUMENT_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.bilang.bilang.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.bilang.bilang.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for class '{@link org.xtext.example.bilang.bilang.Task <em>Task</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Task</em>'.
   * @see org.xtext.example.bilang.bilang.Task
   * @generated
   */
  EClass getTask();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.bilang.bilang.Task#getKind <em>Kind</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Kind</em>'.
   * @see org.xtext.example.bilang.bilang.Task#getKind()
   * @see #getTask()
   * @generated
   */
  EReference getTask_Kind();

  /**
   * Returns the meta object for class '{@link org.xtext.example.bilang.bilang.CompoundProcess <em>Compound Process</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Compound Process</em>'.
   * @see org.xtext.example.bilang.bilang.CompoundProcess
   * @generated
   */
  EClass getCompoundProcess();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.bilang.bilang.CompoundProcess#getTask <em>Task</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Task</em>'.
   * @see org.xtext.example.bilang.bilang.CompoundProcess#getTask()
   * @see #getCompoundProcess()
   * @generated
   */
  EReference getCompoundProcess_Task();

  /**
   * Returns the meta object for class '{@link org.xtext.example.bilang.bilang.AbstractProcess <em>Abstract Process</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Abstract Process</em>'.
   * @see org.xtext.example.bilang.bilang.AbstractProcess
   * @generated
   */
  EClass getAbstractProcess();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.bilang.bilang.AbstractProcess#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.bilang.bilang.AbstractProcess#getName()
   * @see #getAbstractProcess()
   * @generated
   */
  EAttribute getAbstractProcess_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.bilang.bilang.AbstractProcess#getParamValues <em>Param Values</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Param Values</em>'.
   * @see org.xtext.example.bilang.bilang.AbstractProcess#getParamValues()
   * @see #getAbstractProcess()
   * @generated
   */
  EReference getAbstractProcess_ParamValues();

  /**
   * Returns the meta object for class '{@link org.xtext.example.bilang.bilang.ParamValue <em>Param Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Param Value</em>'.
   * @see org.xtext.example.bilang.bilang.ParamValue
   * @generated
   */
  EClass getParamValue();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.bilang.bilang.ParamValue#getParam <em>Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Param</em>'.
   * @see org.xtext.example.bilang.bilang.ParamValue#getParam()
   * @see #getParamValue()
   * @generated
   */
  EAttribute getParamValue_Param();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.bilang.bilang.ParamValue#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.bilang.bilang.ParamValue#getValue()
   * @see #getParamValue()
   * @generated
   */
  EAttribute getParamValue_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.bilang.bilang.RetrieveTask <em>Retrieve Task</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Retrieve Task</em>'.
   * @see org.xtext.example.bilang.bilang.RetrieveTask
   * @generated
   */
  EClass getRetrieveTask();

  /**
   * Returns the meta object for class '{@link org.xtext.example.bilang.bilang.SendTask <em>Send Task</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Send Task</em>'.
   * @see org.xtext.example.bilang.bilang.SendTask
   * @generated
   */
  EClass getSendTask();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.bilang.bilang.SendTask#getPerson <em>Person</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Person</em>'.
   * @see org.xtext.example.bilang.bilang.SendTask#getPerson()
   * @see #getSendTask()
   * @generated
   */
  EReference getSendTask_Person();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.bilang.bilang.SendTask#getContent <em>Content</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Content</em>'.
   * @see org.xtext.example.bilang.bilang.SendTask#getContent()
   * @see #getSendTask()
   * @generated
   */
  EReference getSendTask_Content();

  /**
   * Returns the meta object for class '{@link org.xtext.example.bilang.bilang.PersonTask <em>Person Task</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Person Task</em>'.
   * @see org.xtext.example.bilang.bilang.PersonTask
   * @generated
   */
  EClass getPersonTask();

  /**
   * Returns the meta object for class '{@link org.xtext.example.bilang.bilang.SendEmail <em>Send Email</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Send Email</em>'.
   * @see org.xtext.example.bilang.bilang.SendEmail
   * @generated
   */
  EClass getSendEmail();

  /**
   * Returns the meta object for class '{@link org.xtext.example.bilang.bilang.SendSMS <em>Send SMS</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Send SMS</em>'.
   * @see org.xtext.example.bilang.bilang.SendSMS
   * @generated
   */
  EClass getSendSMS();

  /**
   * Returns the meta object for class '{@link org.xtext.example.bilang.bilang.SendSnailMail <em>Send Snail Mail</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Send Snail Mail</em>'.
   * @see org.xtext.example.bilang.bilang.SendSnailMail
   * @generated
   */
  EClass getSendSnailMail();

  /**
   * Returns the meta object for class '{@link org.xtext.example.bilang.bilang.RetrieveDocument <em>Retrieve Document</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Retrieve Document</em>'.
   * @see org.xtext.example.bilang.bilang.RetrieveDocument
   * @generated
   */
  EClass getRetrieveDocument();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.bilang.bilang.RetrieveDocument#getDocument <em>Document</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Document</em>'.
   * @see org.xtext.example.bilang.bilang.RetrieveDocument#getDocument()
   * @see #getRetrieveDocument()
   * @generated
   */
  EReference getRetrieveDocument_Document();

  /**
   * Returns the meta object for class '{@link org.xtext.example.bilang.bilang.RetrieveFullAddress <em>Retrieve Full Address</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Retrieve Full Address</em>'.
   * @see org.xtext.example.bilang.bilang.RetrieveFullAddress
   * @generated
   */
  EClass getRetrieveFullAddress();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.bilang.bilang.RetrieveFullAddress#getPersonAdress <em>Person Adress</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Person Adress</em>'.
   * @see org.xtext.example.bilang.bilang.RetrieveFullAddress#getPersonAdress()
   * @see #getRetrieveFullAddress()
   * @generated
   */
  EReference getRetrieveFullAddress_PersonAdress();

  /**
   * Returns the meta object for class '{@link org.xtext.example.bilang.bilang.RetrievePersons <em>Retrieve Persons</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Retrieve Persons</em>'.
   * @see org.xtext.example.bilang.bilang.RetrievePersons
   * @generated
   */
  EClass getRetrievePersons();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.bilang.bilang.RetrievePersons#getPersonSearch <em>Person Search</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Person Search</em>'.
   * @see org.xtext.example.bilang.bilang.RetrievePersons#getPersonSearch()
   * @see #getRetrievePersons()
   * @generated
   */
  EAttribute getRetrievePersons_PersonSearch();

  /**
   * Returns the meta object for class '{@link org.xtext.example.bilang.bilang.CallPerson <em>Call Person</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Call Person</em>'.
   * @see org.xtext.example.bilang.bilang.CallPerson
   * @generated
   */
  EClass getCallPerson();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.bilang.bilang.CallPerson#getPerson <em>Person</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Person</em>'.
   * @see org.xtext.example.bilang.bilang.CallPerson#getPerson()
   * @see #getCallPerson()
   * @generated
   */
  EReference getCallPerson_Person();

  /**
   * Returns the meta object for class '{@link org.xtext.example.bilang.bilang.AddPerson <em>Add Person</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Add Person</em>'.
   * @see org.xtext.example.bilang.bilang.AddPerson
   * @generated
   */
  EClass getAddPerson();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.bilang.bilang.AddPerson#getAlias <em>Alias</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Alias</em>'.
   * @see org.xtext.example.bilang.bilang.AddPerson#getAlias()
   * @see #getAddPerson()
   * @generated
   */
  EReference getAddPerson_Alias();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.bilang.bilang.AddPerson#getPerson <em>Person</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Person</em>'.
   * @see org.xtext.example.bilang.bilang.AddPerson#getPerson()
   * @see #getAddPerson()
   * @generated
   */
  EReference getAddPerson_Person();

  /**
   * Returns the meta object for class '{@link org.xtext.example.bilang.bilang.DeletePerson <em>Delete Person</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Delete Person</em>'.
   * @see org.xtext.example.bilang.bilang.DeletePerson
   * @generated
   */
  EClass getDeletePerson();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.bilang.bilang.DeletePerson#getAlias <em>Alias</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Alias</em>'.
   * @see org.xtext.example.bilang.bilang.DeletePerson#getAlias()
   * @see #getDeletePerson()
   * @generated
   */
  EReference getDeletePerson_Alias();

  /**
   * Returns the meta object for class '{@link org.xtext.example.bilang.bilang.Person <em>Person</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Person</em>'.
   * @see org.xtext.example.bilang.bilang.Person
   * @generated
   */
  EClass getPerson();

  /**
   * Returns the meta object for class '{@link org.xtext.example.bilang.bilang.PersonByEmail <em>Person By Email</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Person By Email</em>'.
   * @see org.xtext.example.bilang.bilang.PersonByEmail
   * @generated
   */
  EClass getPersonByEmail();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.bilang.bilang.PersonByEmail#getEmailaddress <em>Emailaddress</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Emailaddress</em>'.
   * @see org.xtext.example.bilang.bilang.PersonByEmail#getEmailaddress()
   * @see #getPersonByEmail()
   * @generated
   */
  EAttribute getPersonByEmail_Emailaddress();

  /**
   * Returns the meta object for class '{@link org.xtext.example.bilang.bilang.PersonByAlias <em>Person By Alias</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Person By Alias</em>'.
   * @see org.xtext.example.bilang.bilang.PersonByAlias
   * @generated
   */
  EClass getPersonByAlias();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.bilang.bilang.PersonByAlias#getAlias <em>Alias</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Alias</em>'.
   * @see org.xtext.example.bilang.bilang.PersonByAlias#getAlias()
   * @see #getPersonByAlias()
   * @generated
   */
  EAttribute getPersonByAlias_Alias();

  /**
   * Returns the meta object for class '{@link org.xtext.example.bilang.bilang.PersonByName <em>Person By Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Person By Name</em>'.
   * @see org.xtext.example.bilang.bilang.PersonByName
   * @generated
   */
  EClass getPersonByName();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.bilang.bilang.PersonByName#getFirstName <em>First Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>First Name</em>'.
   * @see org.xtext.example.bilang.bilang.PersonByName#getFirstName()
   * @see #getPersonByName()
   * @generated
   */
  EAttribute getPersonByName_FirstName();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.bilang.bilang.PersonByName#getLastName <em>Last Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Last Name</em>'.
   * @see org.xtext.example.bilang.bilang.PersonByName#getLastName()
   * @see #getPersonByName()
   * @generated
   */
  EAttribute getPersonByName_LastName();

  /**
   * Returns the meta object for class '{@link org.xtext.example.bilang.bilang.PersonByPhone <em>Person By Phone</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Person By Phone</em>'.
   * @see org.xtext.example.bilang.bilang.PersonByPhone
   * @generated
   */
  EClass getPersonByPhone();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.bilang.bilang.PersonByPhone#getPhone <em>Phone</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Phone</em>'.
   * @see org.xtext.example.bilang.bilang.PersonByPhone#getPhone()
   * @see #getPersonByPhone()
   * @generated
   */
  EAttribute getPersonByPhone_Phone();

  /**
   * Returns the meta object for class '{@link org.xtext.example.bilang.bilang.PersonByAddress <em>Person By Address</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Person By Address</em>'.
   * @see org.xtext.example.bilang.bilang.PersonByAddress
   * @generated
   */
  EClass getPersonByAddress();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.bilang.bilang.PersonByAddress#getZipcode <em>Zipcode</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Zipcode</em>'.
   * @see org.xtext.example.bilang.bilang.PersonByAddress#getZipcode()
   * @see #getPersonByAddress()
   * @generated
   */
  EAttribute getPersonByAddress_Zipcode();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.bilang.bilang.PersonByAddress#getHousenumber <em>Housenumber</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Housenumber</em>'.
   * @see org.xtext.example.bilang.bilang.PersonByAddress#getHousenumber()
   * @see #getPersonByAddress()
   * @generated
   */
  EAttribute getPersonByAddress_Housenumber();

  /**
   * Returns the meta object for class '{@link org.xtext.example.bilang.bilang.Content <em>Content</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Content</em>'.
   * @see org.xtext.example.bilang.bilang.Content
   * @generated
   */
  EClass getContent();

  /**
   * Returns the meta object for class '{@link org.xtext.example.bilang.bilang.Message <em>Message</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Message</em>'.
   * @see org.xtext.example.bilang.bilang.Message
   * @generated
   */
  EClass getMessage();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.bilang.bilang.Message#getMessage <em>Message</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Message</em>'.
   * @see org.xtext.example.bilang.bilang.Message#getMessage()
   * @see #getMessage()
   * @generated
   */
  EAttribute getMessage_Message();

  /**
   * Returns the meta object for class '{@link org.xtext.example.bilang.bilang.Document <em>Document</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Document</em>'.
   * @see org.xtext.example.bilang.bilang.Document
   * @generated
   */
  EClass getDocument();

  /**
   * Returns the meta object for class '{@link org.xtext.example.bilang.bilang.Invoice <em>Invoice</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Invoice</em>'.
   * @see org.xtext.example.bilang.bilang.Invoice
   * @generated
   */
  EClass getInvoice();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.bilang.bilang.Invoice#getCode <em>Code</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Code</em>'.
   * @see org.xtext.example.bilang.bilang.Invoice#getCode()
   * @see #getInvoice()
   * @generated
   */
  EAttribute getInvoice_Code();

  /**
   * Returns the meta object for class '{@link org.xtext.example.bilang.bilang.DocumentPerson <em>Document Person</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Document Person</em>'.
   * @see org.xtext.example.bilang.bilang.DocumentPerson
   * @generated
   */
  EClass getDocumentPerson();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.bilang.bilang.DocumentPerson#getPerson <em>Person</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Person</em>'.
   * @see org.xtext.example.bilang.bilang.DocumentPerson#getPerson()
   * @see #getDocumentPerson()
   * @generated
   */
  EReference getDocumentPerson_Person();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  BilangFactory getBilangFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.bilang.bilang.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.bilang.bilang.impl.ModelImpl
     * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '{@link org.xtext.example.bilang.bilang.impl.TaskImpl <em>Task</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.bilang.bilang.impl.TaskImpl
     * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getTask()
     * @generated
     */
    EClass TASK = eINSTANCE.getTask();

    /**
     * The meta object literal for the '<em><b>Kind</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TASK__KIND = eINSTANCE.getTask_Kind();

    /**
     * The meta object literal for the '{@link org.xtext.example.bilang.bilang.impl.CompoundProcessImpl <em>Compound Process</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.bilang.bilang.impl.CompoundProcessImpl
     * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getCompoundProcess()
     * @generated
     */
    EClass COMPOUND_PROCESS = eINSTANCE.getCompoundProcess();

    /**
     * The meta object literal for the '<em><b>Task</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPOUND_PROCESS__TASK = eINSTANCE.getCompoundProcess_Task();

    /**
     * The meta object literal for the '{@link org.xtext.example.bilang.bilang.impl.AbstractProcessImpl <em>Abstract Process</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.bilang.bilang.impl.AbstractProcessImpl
     * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getAbstractProcess()
     * @generated
     */
    EClass ABSTRACT_PROCESS = eINSTANCE.getAbstractProcess();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ABSTRACT_PROCESS__NAME = eINSTANCE.getAbstractProcess_Name();

    /**
     * The meta object literal for the '<em><b>Param Values</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ABSTRACT_PROCESS__PARAM_VALUES = eINSTANCE.getAbstractProcess_ParamValues();

    /**
     * The meta object literal for the '{@link org.xtext.example.bilang.bilang.impl.ParamValueImpl <em>Param Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.bilang.bilang.impl.ParamValueImpl
     * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getParamValue()
     * @generated
     */
    EClass PARAM_VALUE = eINSTANCE.getParamValue();

    /**
     * The meta object literal for the '<em><b>Param</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAM_VALUE__PARAM = eINSTANCE.getParamValue_Param();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAM_VALUE__VALUE = eINSTANCE.getParamValue_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.bilang.bilang.impl.RetrieveTaskImpl <em>Retrieve Task</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.bilang.bilang.impl.RetrieveTaskImpl
     * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getRetrieveTask()
     * @generated
     */
    EClass RETRIEVE_TASK = eINSTANCE.getRetrieveTask();

    /**
     * The meta object literal for the '{@link org.xtext.example.bilang.bilang.impl.SendTaskImpl <em>Send Task</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.bilang.bilang.impl.SendTaskImpl
     * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getSendTask()
     * @generated
     */
    EClass SEND_TASK = eINSTANCE.getSendTask();

    /**
     * The meta object literal for the '<em><b>Person</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SEND_TASK__PERSON = eINSTANCE.getSendTask_Person();

    /**
     * The meta object literal for the '<em><b>Content</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SEND_TASK__CONTENT = eINSTANCE.getSendTask_Content();

    /**
     * The meta object literal for the '{@link org.xtext.example.bilang.bilang.impl.PersonTaskImpl <em>Person Task</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.bilang.bilang.impl.PersonTaskImpl
     * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getPersonTask()
     * @generated
     */
    EClass PERSON_TASK = eINSTANCE.getPersonTask();

    /**
     * The meta object literal for the '{@link org.xtext.example.bilang.bilang.impl.SendEmailImpl <em>Send Email</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.bilang.bilang.impl.SendEmailImpl
     * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getSendEmail()
     * @generated
     */
    EClass SEND_EMAIL = eINSTANCE.getSendEmail();

    /**
     * The meta object literal for the '{@link org.xtext.example.bilang.bilang.impl.SendSMSImpl <em>Send SMS</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.bilang.bilang.impl.SendSMSImpl
     * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getSendSMS()
     * @generated
     */
    EClass SEND_SMS = eINSTANCE.getSendSMS();

    /**
     * The meta object literal for the '{@link org.xtext.example.bilang.bilang.impl.SendSnailMailImpl <em>Send Snail Mail</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.bilang.bilang.impl.SendSnailMailImpl
     * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getSendSnailMail()
     * @generated
     */
    EClass SEND_SNAIL_MAIL = eINSTANCE.getSendSnailMail();

    /**
     * The meta object literal for the '{@link org.xtext.example.bilang.bilang.impl.RetrieveDocumentImpl <em>Retrieve Document</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.bilang.bilang.impl.RetrieveDocumentImpl
     * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getRetrieveDocument()
     * @generated
     */
    EClass RETRIEVE_DOCUMENT = eINSTANCE.getRetrieveDocument();

    /**
     * The meta object literal for the '<em><b>Document</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RETRIEVE_DOCUMENT__DOCUMENT = eINSTANCE.getRetrieveDocument_Document();

    /**
     * The meta object literal for the '{@link org.xtext.example.bilang.bilang.impl.RetrieveFullAddressImpl <em>Retrieve Full Address</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.bilang.bilang.impl.RetrieveFullAddressImpl
     * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getRetrieveFullAddress()
     * @generated
     */
    EClass RETRIEVE_FULL_ADDRESS = eINSTANCE.getRetrieveFullAddress();

    /**
     * The meta object literal for the '<em><b>Person Adress</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RETRIEVE_FULL_ADDRESS__PERSON_ADRESS = eINSTANCE.getRetrieveFullAddress_PersonAdress();

    /**
     * The meta object literal for the '{@link org.xtext.example.bilang.bilang.impl.RetrievePersonsImpl <em>Retrieve Persons</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.bilang.bilang.impl.RetrievePersonsImpl
     * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getRetrievePersons()
     * @generated
     */
    EClass RETRIEVE_PERSONS = eINSTANCE.getRetrievePersons();

    /**
     * The meta object literal for the '<em><b>Person Search</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RETRIEVE_PERSONS__PERSON_SEARCH = eINSTANCE.getRetrievePersons_PersonSearch();

    /**
     * The meta object literal for the '{@link org.xtext.example.bilang.bilang.impl.CallPersonImpl <em>Call Person</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.bilang.bilang.impl.CallPersonImpl
     * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getCallPerson()
     * @generated
     */
    EClass CALL_PERSON = eINSTANCE.getCallPerson();

    /**
     * The meta object literal for the '<em><b>Person</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CALL_PERSON__PERSON = eINSTANCE.getCallPerson_Person();

    /**
     * The meta object literal for the '{@link org.xtext.example.bilang.bilang.impl.AddPersonImpl <em>Add Person</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.bilang.bilang.impl.AddPersonImpl
     * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getAddPerson()
     * @generated
     */
    EClass ADD_PERSON = eINSTANCE.getAddPerson();

    /**
     * The meta object literal for the '<em><b>Alias</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADD_PERSON__ALIAS = eINSTANCE.getAddPerson_Alias();

    /**
     * The meta object literal for the '<em><b>Person</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADD_PERSON__PERSON = eINSTANCE.getAddPerson_Person();

    /**
     * The meta object literal for the '{@link org.xtext.example.bilang.bilang.impl.DeletePersonImpl <em>Delete Person</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.bilang.bilang.impl.DeletePersonImpl
     * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getDeletePerson()
     * @generated
     */
    EClass DELETE_PERSON = eINSTANCE.getDeletePerson();

    /**
     * The meta object literal for the '<em><b>Alias</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DELETE_PERSON__ALIAS = eINSTANCE.getDeletePerson_Alias();

    /**
     * The meta object literal for the '{@link org.xtext.example.bilang.bilang.impl.PersonImpl <em>Person</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.bilang.bilang.impl.PersonImpl
     * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getPerson()
     * @generated
     */
    EClass PERSON = eINSTANCE.getPerson();

    /**
     * The meta object literal for the '{@link org.xtext.example.bilang.bilang.impl.PersonByEmailImpl <em>Person By Email</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.bilang.bilang.impl.PersonByEmailImpl
     * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getPersonByEmail()
     * @generated
     */
    EClass PERSON_BY_EMAIL = eINSTANCE.getPersonByEmail();

    /**
     * The meta object literal for the '<em><b>Emailaddress</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSON_BY_EMAIL__EMAILADDRESS = eINSTANCE.getPersonByEmail_Emailaddress();

    /**
     * The meta object literal for the '{@link org.xtext.example.bilang.bilang.impl.PersonByAliasImpl <em>Person By Alias</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.bilang.bilang.impl.PersonByAliasImpl
     * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getPersonByAlias()
     * @generated
     */
    EClass PERSON_BY_ALIAS = eINSTANCE.getPersonByAlias();

    /**
     * The meta object literal for the '<em><b>Alias</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSON_BY_ALIAS__ALIAS = eINSTANCE.getPersonByAlias_Alias();

    /**
     * The meta object literal for the '{@link org.xtext.example.bilang.bilang.impl.PersonByNameImpl <em>Person By Name</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.bilang.bilang.impl.PersonByNameImpl
     * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getPersonByName()
     * @generated
     */
    EClass PERSON_BY_NAME = eINSTANCE.getPersonByName();

    /**
     * The meta object literal for the '<em><b>First Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSON_BY_NAME__FIRST_NAME = eINSTANCE.getPersonByName_FirstName();

    /**
     * The meta object literal for the '<em><b>Last Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSON_BY_NAME__LAST_NAME = eINSTANCE.getPersonByName_LastName();

    /**
     * The meta object literal for the '{@link org.xtext.example.bilang.bilang.impl.PersonByPhoneImpl <em>Person By Phone</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.bilang.bilang.impl.PersonByPhoneImpl
     * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getPersonByPhone()
     * @generated
     */
    EClass PERSON_BY_PHONE = eINSTANCE.getPersonByPhone();

    /**
     * The meta object literal for the '<em><b>Phone</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSON_BY_PHONE__PHONE = eINSTANCE.getPersonByPhone_Phone();

    /**
     * The meta object literal for the '{@link org.xtext.example.bilang.bilang.impl.PersonByAddressImpl <em>Person By Address</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.bilang.bilang.impl.PersonByAddressImpl
     * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getPersonByAddress()
     * @generated
     */
    EClass PERSON_BY_ADDRESS = eINSTANCE.getPersonByAddress();

    /**
     * The meta object literal for the '<em><b>Zipcode</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSON_BY_ADDRESS__ZIPCODE = eINSTANCE.getPersonByAddress_Zipcode();

    /**
     * The meta object literal for the '<em><b>Housenumber</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSON_BY_ADDRESS__HOUSENUMBER = eINSTANCE.getPersonByAddress_Housenumber();

    /**
     * The meta object literal for the '{@link org.xtext.example.bilang.bilang.impl.ContentImpl <em>Content</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.bilang.bilang.impl.ContentImpl
     * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getContent()
     * @generated
     */
    EClass CONTENT = eINSTANCE.getContent();

    /**
     * The meta object literal for the '{@link org.xtext.example.bilang.bilang.impl.MessageImpl <em>Message</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.bilang.bilang.impl.MessageImpl
     * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getMessage()
     * @generated
     */
    EClass MESSAGE = eINSTANCE.getMessage();

    /**
     * The meta object literal for the '<em><b>Message</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MESSAGE__MESSAGE = eINSTANCE.getMessage_Message();

    /**
     * The meta object literal for the '{@link org.xtext.example.bilang.bilang.impl.DocumentImpl <em>Document</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.bilang.bilang.impl.DocumentImpl
     * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getDocument()
     * @generated
     */
    EClass DOCUMENT = eINSTANCE.getDocument();

    /**
     * The meta object literal for the '{@link org.xtext.example.bilang.bilang.impl.InvoiceImpl <em>Invoice</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.bilang.bilang.impl.InvoiceImpl
     * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getInvoice()
     * @generated
     */
    EClass INVOICE = eINSTANCE.getInvoice();

    /**
     * The meta object literal for the '<em><b>Code</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INVOICE__CODE = eINSTANCE.getInvoice_Code();

    /**
     * The meta object literal for the '{@link org.xtext.example.bilang.bilang.impl.DocumentPersonImpl <em>Document Person</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.bilang.bilang.impl.DocumentPersonImpl
     * @see org.xtext.example.bilang.bilang.impl.BilangPackageImpl#getDocumentPerson()
     * @generated
     */
    EClass DOCUMENT_PERSON = eINSTANCE.getDocumentPerson();

    /**
     * The meta object literal for the '<em><b>Person</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DOCUMENT_PERSON__PERSON = eINSTANCE.getDocumentPerson_Person();

  }

} //BilangPackage
