/**
 * generated by Xtext 2.44.0
 */
package org.xtext.example.bilang.bilang;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Compound Process</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.bilang.bilang.CompoundProcess#getTask <em>Task</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.bilang.bilang.BilangPackage#getCompoundProcess()
 * @model
 * @generated
 */
public interface CompoundProcess extends Model
{
  /**
   * Returns the value of the '<em><b>Task</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.bilang.bilang.Task}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Task</em>' containment reference list.
   * @see org.xtext.example.bilang.bilang.BilangPackage#getCompoundProcess_Task()
   * @model containment="true"
   * @generated
   */
  EList<Task> getTask();

} // CompoundProcess
