/**
 * generated by Xtext 2.44.0
 */
package org.xtext.example.bilang.bilang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Delete Person</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.bilang.bilang.DeletePerson#getAlias <em>Alias</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.bilang.bilang.BilangPackage#getDeletePerson()
 * @model
 * @generated
 */
public interface DeletePerson extends PersonTask
{
  /**
   * Returns the value of the '<em><b>Alias</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Alias</em>' containment reference.
   * @see #setAlias(PersonByAlias)
   * @see org.xtext.example.bilang.bilang.BilangPackage#getDeletePerson_Alias()
   * @model containment="true"
   * @generated
   */
  PersonByAlias getAlias();

  /**
   * Sets the value of the '{@link org.xtext.example.bilang.bilang.DeletePerson#getAlias <em>Alias</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Alias</em>' containment reference.
   * @see #getAlias()
   * @generated
   */
  void setAlias(PersonByAlias value);

} // DeletePerson
