/**
 * generated by Xtext 2.44.0
 */
package org.xtext.example.bilang.bilang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Document</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.bilang.bilang.BilangPackage#getDocument()
 * @model
 * @generated
 */
public interface Document extends Content
{
} // Document
