/**
 * generated by Xtext 2.44.0
 */
package org.xtext.example.bilang.bilang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Document Person</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.bilang.bilang.DocumentPerson#getPerson <em>Person</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.bilang.bilang.BilangPackage#getDocumentPerson()
 * @model
 * @generated
 */
public interface DocumentPerson extends Document
{
  /**
   * Returns the value of the '<em><b>Person</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Person</em>' containment reference.
   * @see #setPerson(Person)
   * @see org.xtext.example.bilang.bilang.BilangPackage#getDocumentPerson_Person()
   * @model containment="true"
   * @generated
   */
  Person getPerson();

  /**
   * Sets the value of the '{@link org.xtext.example.bilang.bilang.DocumentPerson#getPerson <em>Person</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Person</em>' containment reference.
   * @see #getPerson()
   * @generated
   */
  void setPerson(Person value);

} // DocumentPerson
