/**
 * generated by Xtext 2.44.0
 */
package org.xtext.example.bilang.bilang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Person Task</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.bilang.bilang.BilangPackage#getPersonTask()
 * @model
 * @generated
 */
public interface PersonTask extends EObject
{
} // PersonTask
