/**
 * generated by Xtext 2.44.0
 */
package org.xtext.example.bilang.bilang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Person By Address</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.bilang.bilang.PersonByAddress#getZipcode <em>Zipcode</em>}</li>
 *   <li>{@link org.xtext.example.bilang.bilang.PersonByAddress#getHousenumber <em>Housenumber</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.bilang.bilang.BilangPackage#getPersonByAddress()
 * @model
 * @generated
 */
public interface PersonByAddress extends Person
{
  /**
   * Returns the value of the '<em><b>Zipcode</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Zipcode</em>' attribute.
   * @see #setZipcode(String)
   * @see org.xtext.example.bilang.bilang.BilangPackage#getPersonByAddress_Zipcode()
   * @model
   * @generated
   */
  String getZipcode();

  /**
   * Sets the value of the '{@link org.xtext.example.bilang.bilang.PersonByAddress#getZipcode <em>Zipcode</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Zipcode</em>' attribute.
   * @see #getZipcode()
   * @generated
   */
  void setZipcode(String value);

  /**
   * Returns the value of the '<em><b>Housenumber</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Housenumber</em>' attribute.
   * @see #setHousenumber(String)
   * @see org.xtext.example.bilang.bilang.BilangPackage#getPersonByAddress_Housenumber()
   * @model
   * @generated
   */
  String getHousenumber();

  /**
   * Sets the value of the '{@link org.xtext.example.bilang.bilang.PersonByAddress#getHousenumber <em>Housenumber</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Housenumber</em>' attribute.
   * @see #getHousenumber()
   * @generated
   */
  void setHousenumber(String value);

} // PersonByAddress
