/**
 * generated by Xtext 2.44.0
 */
package org.xtext.example.bilang.bilang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Person By Email</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.bilang.bilang.PersonByEmail#getEmailaddress <em>Emailaddress</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.bilang.bilang.BilangPackage#getPersonByEmail()
 * @model
 * @generated
 */
public interface PersonByEmail extends Person
{
  /**
   * Returns the value of the '<em><b>Emailaddress</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Emailaddress</em>' attribute.
   * @see #setEmailaddress(String)
   * @see org.xtext.example.bilang.bilang.BilangPackage#getPersonByEmail_Emailaddress()
   * @model
   * @generated
   */
  String getEmailaddress();

  /**
   * Sets the value of the '{@link org.xtext.example.bilang.bilang.PersonByEmail#getEmailaddress <em>Emailaddress</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Emailaddress</em>' attribute.
   * @see #getEmailaddress()
   * @generated
   */
  void setEmailaddress(String value);

} // PersonByEmail
