/**
 * generated by Xtext 2.44.0
 */
package org.xtext.example.bilang.bilang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Person By Phone</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.bilang.bilang.PersonByPhone#getPhone <em>Phone</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.bilang.bilang.BilangPackage#getPersonByPhone()
 * @model
 * @generated
 */
public interface PersonByPhone extends Person
{
  /**
   * Returns the value of the '<em><b>Phone</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Phone</em>' attribute.
   * @see #setPhone(String)
   * @see org.xtext.example.bilang.bilang.BilangPackage#getPersonByPhone_Phone()
   * @model
   * @generated
   */
  String getPhone();

  /**
   * Sets the value of the '{@link org.xtext.example.bilang.bilang.PersonByPhone#getPhone <em>Phone</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Phone</em>' attribute.
   * @see #getPhone()
   * @generated
   */
  void setPhone(String value);

} // PersonByPhone
