/**
 * generated by Xtext 2.44.0
 */
package org.xtext.example.bilang.bilang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Retrieve Document</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.bilang.bilang.RetrieveDocument#getDocument <em>Document</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.bilang.bilang.BilangPackage#getRetrieveDocument()
 * @model
 * @generated
 */
public interface RetrieveDocument extends RetrieveTask
{
  /**
   * Returns the value of the '<em><b>Document</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Document</em>' containment reference.
   * @see #setDocument(Document)
   * @see org.xtext.example.bilang.bilang.BilangPackage#getRetrieveDocument_Document()
   * @model containment="true"
   * @generated
   */
  Document getDocument();

  /**
   * Sets the value of the '{@link org.xtext.example.bilang.bilang.RetrieveDocument#getDocument <em>Document</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Document</em>' containment reference.
   * @see #getDocument()
   * @generated
   */
  void setDocument(Document value);

} // RetrieveDocument
