/**
 * generated by Xtext 2.44.0
 */
package org.xtext.example.bilang.bilang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Retrieve Persons</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.bilang.bilang.RetrievePersons#getPersonSearch <em>Person Search</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.bilang.bilang.BilangPackage#getRetrievePersons()
 * @model
 * @generated
 */
public interface RetrievePersons extends RetrieveTask
{
  /**
   * Returns the value of the '<em><b>Person Search</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Person Search</em>' attribute.
   * @see #setPersonSearch(String)
   * @see org.xtext.example.bilang.bilang.BilangPackage#getRetrievePersons_PersonSearch()
   * @model
   * @generated
   */
  String getPersonSearch();

  /**
   * Sets the value of the '{@link org.xtext.example.bilang.bilang.RetrievePersons#getPersonSearch <em>Person Search</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Person Search</em>' attribute.
   * @see #getPersonSearch()
   * @generated
   */
  void setPersonSearch(String value);

} // RetrievePersons
