/**
 * generated by Xtext 2.44.0
 */
package org.xtext.example.bilang.bilang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Retrieve Full Address</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.bilang.bilang.RetrieveFullAddress#getPersonAdress <em>Person Adress</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.bilang.bilang.BilangPackage#getRetrieveFullAddress()
 * @model
 * @generated
 */
public interface RetrieveFullAddress extends RetrieveTask
{
  /**
   * Returns the value of the '<em><b>Person Adress</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Person Adress</em>' containment reference.
   * @see #setPersonAdress(PersonByAddress)
   * @see org.xtext.example.bilang.bilang.BilangPackage#getRetrieveFullAddress_PersonAdress()
   * @model containment="true"
   * @generated
   */
  PersonByAddress getPersonAdress();

  /**
   * Sets the value of the '{@link org.xtext.example.bilang.bilang.RetrieveFullAddress#getPersonAdress <em>Person Adress</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Person Adress</em>' containment reference.
   * @see #getPersonAdress()
   * @generated
   */
  void setPersonAdress(PersonByAddress value);

} // RetrieveFullAddress
