/**
 * generated by Xtext 2.44.0
 */
package org.xtext.example.bilang.bilang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Send SMS</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.bilang.bilang.BilangPackage#getSendSMS()
 * @model
 * @generated
 */
public interface SendSMS extends SendTask
{
} // SendSMS
