/**
 * generated by Xtext 2.44.0
 */
package org.xtext.example.bilang.bilang;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Send Task</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.bilang.bilang.SendTask#getPerson <em>Person</em>}</li>
 *   <li>{@link org.xtext.example.bilang.bilang.SendTask#getContent <em>Content</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.bilang.bilang.BilangPackage#getSendTask()
 * @model
 * @generated
 */
public interface SendTask extends Task
{
  /**
   * Returns the value of the '<em><b>Person</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.bilang.bilang.Person}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Person</em>' containment reference list.
   * @see org.xtext.example.bilang.bilang.BilangPackage#getSendTask_Person()
   * @model containment="true"
   * @generated
   */
  EList<Person> getPerson();

  /**
   * Returns the value of the '<em><b>Content</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Content</em>' containment reference.
   * @see #setContent(Content)
   * @see org.xtext.example.bilang.bilang.BilangPackage#getSendTask_Content()
   * @model containment="true"
   * @generated
   */
  Content getContent();

  /**
   * Sets the value of the '{@link org.xtext.example.bilang.bilang.SendTask#getContent <em>Content</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Content</em>' containment reference.
   * @see #getContent()
   * @generated
   */
  void setContent(Content value);

} // SendTask
