/**
 * generated by Xtext 2.44.0
 */
package org.xtext.example.bilang.bilang;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Text With Spaces</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.bilang.bilang.TextWithSpaces#getParts <em>Parts</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.bilang.bilang.BilangPackage#getTextWithSpaces()
 * @model
 * @generated
 */
public interface TextWithSpaces extends EObject
{
  /**
   * Returns the value of the '<em><b>Parts</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parts</em>' attribute list.
   * @see org.xtext.example.bilang.bilang.BilangPackage#getTextWithSpaces_Parts()
   * @model unique="false"
   * @generated
   */
  EList<String> getParts();

} // TextWithSpaces
